export const carMakes: string[] = [
  'Abarth', 'Acura', 'Alfa Romeo', 'Arcfox', 'Aston Martin', 'Audi', 'Avatr', 'BAIC', 'Bentley', 'Bestune',
  'BMW', 'Borgward', 'Brilliance', 'Bugatti', 'BYD', 'Cadillac', 'Caterham', 'Changan', 'Chery', 'Chevrolet',
  'Chrysler', 'Citroen', 'Daihatsu', 'Deepal', 'Denza', 'DFSK', 'Dodge', 'Dongfeng', 'Dorcen', 'Exeed',
  'Fangchengbao', 'Ferrari', 'Fiat', 'Fisker', 'Ford', 'Forthing', 'Foton', 'GAC', 'Geely', 'Genesis',
  'GMC', 'Great Wall', 'Haval', 'Honda', 'Hongqi', 'Hummer', 'Hyundai', 'Hyptec', 'Ineos', 'Infiniti',
  'International', 'Isuzu', 'JAC', 'Jaecoo', 'Jaguar', 'Jeep', 'Jetour', 'Kaiyi', 'Kia', 'King Long',
  'Koenigsegg', 'KTM', 'Lamborghini', 'Land Rover', 'Leapmotor', 'Lexus', 'Li Auto', 'Lincoln', 'Livan',
  'Lotus', 'LS Auto', 'Lucid', 'Luxgen', 'Lynk & Co', 'Mahindra', 'Maserati', 'Maxus', 'Maybach', 'Mazda',
  'McLaren', 'Mercedes-Benz', 'Mercury', 'MG', 'MINI', 'Mitsubishi', 'Morgan', 'Nio', 'Nissan', 'Noble',
  'Omoda', 'Opel', 'Oullim', 'Pagani', 'Peugeot', 'Polestar', 'Porsche', 'Proton', 'Rabdan', 'Ram',
  'Renault', 'Roewe', 'Rolls Royce', 'Saab', 'Seat', 'Seres', 'Skoda', 'Skywell', 'Smart', 'Soueast',
  'Spyker', 'Ssangyong', 'Subaru', 'Suzuki', 'Tank', 'Tata', 'Tesla', 'Toyota', 'VinFast', 'Volkswagen',
  'Volvo', 'Voyah', 'WEY', 'XPeng', 'Yangwang', 'Zeekr', 'Zotye'
].sort();

// Car models organized by manufacturer
export const carModels: Record<string, string[]> = {
  'Abarth': ['595', '695', '124 Spider', 'Punto Evo', 'Grande Punto', '500', '595 Competizione', '595 Scorpionearo'],
  'Acura': ['MDX', 'TLX', 'RDX', 'NSX', 'ILX', 'Integra', 'RLX', 'TSX', 'RL', 'ZDX'],
  'Alfa Romeo': ['Giulia', 'Stelvio', 'Tonale', 'Quadrifoglio', 'Giulietta', 'Mito', '4C', 'Brera', 'GT Coupe', 'Spider', '159', '156', '147', '166'],
  'Arcfox': ['Alpha S', 'Alpha T', 'GT', 'ECF'],
  'Aston Martin': ['DB11', 'DB12', 'DB7', 'DB9', 'DBS', 'DBX', 'One-77', 'Rapide', 'V12 Vantage', 'V8 Vantage', 'Valour', 'Vanquish', 'Zagato'],
  'Audi': ['A1', 'A3', 'A4', 'A5', 'A6', 'A7', 'A8', 'e-tron', 'e-tron GT', 'Q2', 'Q3', 'Q4 e-tron', 'Q5', 'Q6', 'Q7', 'Q8', 'R8', 'RS 3', 'RS 4', 'RS 5', 'RS 6', 'RS 7', 'RS Q8', 'S3', 'S4', 'S5', 'S6', 'S7', 'S8', 'SQ5', 'SQ7', 'SQ8', 'TT'],
  'Avatr': ['11', '12', '07', '06', 'MMW'],
  'BAIC': ['BJ30', 'BJ40', 'BJ60', 'BJ80', 'X35', 'X55', 'X75', 'U5', 'EU5', 'F40'],
  'Bentley': ['Continental GT', 'Continental GTC', 'Flying Spur', 'Bentayga', 'Mulsanne', 'Azure', 'Arnage', 'Brooklands'],
  'Bestune': ['T77', 'T55', 'B70', 'T90', 'B70s', 'T99', 'T33'],
  'BMW': ['1 Series', '2 Series', '3 Series', '4 Series', '5 Series', '6 Series', '7 Series', '8 Series', 'X1', 'X2', 'X3', 'X4', 'X5', 'X6', 'X7', 'XM', 'Z4', 'i3', 'i4', 'i5', 'i7', 'i8', 'iX', 'M2', 'M3', 'M4', 'M5', 'M6', 'M8'],
  'Borgward': ['BX5', 'BX7', 'BX9', 'BX6'],
  'Brilliance': ['FRV', 'FRV Cross', 'V5', 'H530', 'FSV', 'Zun'],
  'Bugatti': ['Chiron', 'Divo', 'Veyron', 'Tourbillon'],
  'BYD': ['Atto 3', 'Dolphin', 'Seal', 'Seal 7', 'Sealion 7', 'Song Plus', 'Qin Plus', 'Han', 'Shark 6', 'Seagull', 'Yuan Up', 'Tang', 'E5', 'E6', 'S6', 'S7', 'F3', 'F5', 'F6', 'G5', 'G6'],
  'Cadillac': ['Escalade', 'Escalade ESV', 'LYRIQ', 'XT4', 'XT5', 'XT6', 'CT4', 'CT5', 'CT6', 'Celestiq', 'Optiq', 'Lyriq'],
  'Caterham': ['Seven', 'Seven 270', 'Seven 310', 'Seven 420', 'Seven 485'],
  'Changan': ['Alsvin', 'CS35 Plus', 'CS55', 'CS75 Plus', 'CS85', 'CS95', 'Eado', 'Eado Plus', 'UNI-K', 'UNI-T', 'UNI-V', 'Hunter', 'Lumin'],
  'Chery': ['Tiggo 3', 'Tiggo 4', 'Tiggo 5', 'Tiggo 7', 'Tiggo 8', 'Tiggo 4 Pro', 'Tiggo 7 Pro', 'Tiggo 8 Pro', 'Arrizo 3', 'Arrizo 5', 'Arrizo 6', 'Arrizo 7', 'Arrizo 8', 'QQ', 'Windcloud'],
  'Chevrolet': ['Silverado', 'Tahoe', 'Suburban', 'Equinox', 'Traverse', 'Trax', 'Blazer', 'Camaro', 'Corvette', 'Malibu', 'Impala', 'Cruze', 'Sonic', 'Spark', 'Bolt', 'Colorado', 'Express', 'Trailing', 'Aveo', 'Captiva', 'Niva', 'Groove', 'Menlo'],
  'Chrysler': ['300', 'Pacifica', 'Voyager', 'Town & Country', 'Sebring', 'Crossfire', 'PT Cruiser'],
  'Citroen': ['C3', 'C4', 'C5', 'C5 Aircross', 'Berlingo', 'Dispatch', 'Jumpy', 'C-Elysee', 'DS3', 'DS4', 'DS5', 'C2', 'Saxo', 'Xsara'],
  'Daihatsu': ['Terios', 'Sirion', 'YRV', 'Materia', 'Charade', 'Gran Max'],
  'Deepal': ['G318', 'S07', 'S05', 'L07', 'S09'],
  'Denza': ['D9', 'N7', 'N9', 'Z9', 'Z9 GT', 'B5', 'B8'],
  'DFSK': ['Fengon 500', 'Fengon 580', 'Fengon 600', 'Fengon ix5', 'Fengon ix7', 'H30 Cross', 'S30'],
  'Dodge': ['Challenger', 'Charger', 'Durango', 'Hornet', 'Journey', 'Grand Caravan', 'Dart', 'Caliber', 'Nitro', 'Ram', 'Viper', 'Avenger'],
  'Dongfeng': ['Shine Max', 'Shine Mage', 'AX7', 'Fengshen', 'S30', 'H30 Cross'],
  'Dorcen': ['G70', 'G60', 'S60'],
  'Exeed': ['VX', 'TXL', 'LX', 'RX', 'ES', 'ET', 'TXL FL'],
  'Fangchengbao': ['Bao 5', 'Bao 8', 'Tai 3', 'Leopard 3', 'Leopard 5', 'Leopard 7', 'Leopard 9'],
  'Ferrari': ['296 GTB', '296 GTS', '360', '458', '488', '599', '612', '812', 'California', 'F12', 'F430', 'F8', 'FF', 'GTC4', 'LaFerrari', 'Portofino', 'Purosangue', 'Roma', 'SF90', '12Cilindri'],
  'Fiat': ['500', '500X', '500L', 'Punto', 'Bravo', 'Linea', 'Tipo', 'Mobi', 'Cronos', 'Ducato', 'Fiorino', 'Fullback', 'Strada'],
  'Fisker': ['Karma', 'Ocean', 'Ronin'],
  'Ford': ['F-150', 'F-150 Raptor', 'Mustang', 'Mustang Mach-E', 'Bronco', 'Bronco Sport', 'Explorer', 'Expedition', 'Edge', 'Escape', 'EcoSport', 'Kuga', 'Puma', 'Focus', 'Fiesta', 'Fusion', 'Mondeo', 'Taurus', 'Ranger', 'Ranger Raptor', 'Maverick', 'Transit', 'Tourneo', 'Everest', 'Territory'],
  'Forthing': ['T5', 'T5 EVO', 'M4', 'U-Tour', 'Friday'],
  'Foton': ['Tunland', 'View', 'C1', 'Aumark'],
  'GAC': ['GS4', 'GS5', 'GS7', 'GS8', 'GA4', 'GA6', 'GA8', 'GN6', 'GN8', 'Emkoo', 'Empow', 'Aion S', 'Aion Y', 'Aion V', 'Aion LX', 'GS3', 'M8'],
  'Geely': ['Coolray', 'Monjaro', 'Tugella', 'Emgrand', 'Okavango', 'Azkarra', 'Geometry C', 'Geometry E', 'Geometry A', 'Icon', 'Starray', 'Preface', 'Xingyue', 'Galaxy'],
  'Genesis': ['G70', 'G80', 'G90', 'GV60', 'GV70', 'GV80', 'Electrified G80', 'Electrified GV70', 'GV70 EV'],
  'GMC': ['Sierra', 'Yukon', 'Yukon XL', 'Acadia', 'Terrain', 'Canyon', 'Savana', 'Hummer EV'],
  'Great Wall': ['Wingle 5', 'Wingle 6', 'Wingle 7', 'Poer', 'King Kong Poer', 'Florid', 'Hover'],
  'Haval': ['H6', 'H6 GT', 'Jolion', 'Dargo', 'H9', 'H7', 'H8', 'H5', 'M6', 'H2', 'H3', 'Tank 300', 'Tank 500'],
  'Honda': ['Civic', 'Accord', 'CR-V', 'HR-V', 'Pilot', 'Odyssey', 'Ridgeline', 'Fit', 'Insight', 'Passport', 'Element', 'S2000', 'ZR-V', 'Civic Type R'],
  'Hongqi': ['H9', 'HS5', 'HS7', 'E-HS9', 'H5', 'LS7', 'LS5', 'H3', 'E-HS3', 'HQ9'],
  'Hummer': ['H2', 'H3', 'EV', 'EV SUV'],
  'Hyundai': ['Tucson', 'Santa Fe', 'Palisade', 'Creta', 'Venue', 'Kona', 'Ioniq 5', 'Ioniq 6', 'Sonata', 'Elantra', 'Accent', 'Veloster', 'Genesis', 'Staria', 'Stargazer', 'Casper', 'Nexo', 'Santa Cruz', 'i10', 'i20', 'i30', 'i40'],
  'Hyptec': ['HT', 'HL', 'HiPhi'],
  'Ineos': ['Grenadier', 'Quartermaster'],
  'Infiniti': ['Q50', 'Q60', 'Q70', 'QX50', 'QX55', 'QX60', 'QX70', 'QX80', 'EX', 'FX', 'G', 'M', 'JX'],
  'International': ['MXT', 'CXT', 'MXT'],
  'Isuzu': ['D-Max', 'MU-X', 'Trooper', 'Rodeo', 'Axiom'],
  'JAC': ['JS3', 'JS4', 'JS5', 'JS6', 'J7', 'E30X', 'T8', 'Sunray', 'M4', 'S3', 'S4', 'S7'],
  'Jaecoo': ['J5', 'J7', 'J7 SHS', 'J8'],
  'Jaguar': ['F-Pace', 'E-Pace', 'I-Pace', 'F-Type', 'XE', 'XF', 'XJ', 'XK', 'X-Type', 'S-Type'],
  'Jeep': ['Wrangler', 'Wrangler Unlimited', 'Grand Cherokee', 'Grand Cherokee L', 'Cherokee', 'Compass', 'Renegade', 'Gladiator', 'Wagoneer', 'Grand Wagoneer', 'Patriot', 'Liberty'],
  'Jetour': ['G700', 'T1', 'T2', 'Dashing', 'X50', 'X70', 'X70 Plus', 'X90', 'X90 Plus'],
  'Kaiyi': ['X3', 'X7', 'X3 Pro', 'E5'],
  'Kia': ['Telluride', 'Sorento', 'Sportage', 'Seltos', 'Forte', 'K5', 'Carnival', 'EV6', 'EV9', 'Niro', 'Soul', 'Rio', 'Stinger', 'K900', 'Mohave', 'Carens', 'Sonet', 'K4'],
  'King Long': ['XMQ', 'XML', 'XMQ'],
  'Koenigsegg': ['Jesko', 'Regera', 'Agera', 'One:1', 'CCX', 'Gemera'],
  'KTM': ['X-Bow'],
  'Lamborghini': ['Urus', 'Huracan', 'Aventador', 'Gallardo', 'Murcielago', 'Revuelto'],
  'Land Rover': ['Defender', 'Discovery', 'Discovery Sport', 'Range Rover', 'Range Rover Sport', 'Range Rover Evoque', 'Range Rover Velar', 'Freelander'],
  'Leapmotor': ['C11', 'C01', 'T03', 'B10'],
  'Lexus': ['RX', 'NX', 'ES', 'IS', 'GS', 'LS', 'UX', 'LC', 'RC', 'LX', 'GX', 'RZ', 'TX', 'SC'],
  'Li Auto': ['L9', 'L8', 'L7', 'L6', 'MEGA'],
  'Lincoln': ['Navigator', 'Aviator', 'Corsair', 'Nautilus', 'MKZ', 'MKC', 'MKS', 'MKT', 'Town Car'],
  'Livan': ['X6 Pro', 'S6 Pro', 'X3'],
  'Lotus': ['Emira', 'Emeya', 'Eletre', 'Evora', 'Exige', 'Elise', 'Evija'],
  'LS Auto': ['LS500', 'LS350', 'LX500', 'UX200'],
  'Lucid': ['Air', 'Gravity', 'Sapphire'],
  'Luxgen': ['U6', 'U7', 'S5', '7 SUV', '7 MPV'],
  'Lynk & Co': ['01', '02', '03', '03+', '05', '06', '07', '08', '09'],
  'Mahindra': ['Scorpio', 'XUV500', 'XUV300', 'Thar', 'Bolero', 'Marazzo', 'KUV100', 'Alturas', 'XUV700'],
  'Maserati': ['Grecale', 'Levante', 'Ghibli', 'Quattroporte', 'MC20', 'GranTurismo', 'GranCabrio'],
  'Maxus': ['T60', 'T70', 'T90', 'G10', 'G50', 'G90', 'D60', 'D90', 'Mifa'],
  'Maybach': ['S-Class', 'GLS', '57', '62'],
  'Mazda': ['CX-5', 'CX-9', 'CX-30', 'CX-50', 'CX-60', 'CX-90', 'MAZDA3', 'MAZDA6', 'MX-5', 'MX-30', 'CX-3', 'CX-7'],
  'McLaren': ['720S', '750S', '765LT', 'Artura', 'GT', '570S', '600LT', '620R', '675LT', '720S Spider', 'Spider', 'P1', 'Senna', 'Speedtail'],
  'Mercedes-Benz': ['A-Class', 'C-Class', 'E-Class', 'S-Class', 'GLA', 'GLB', 'GLC', 'GLE', 'GLS', 'G-Class', 'CLA', 'CLS', 'SL', 'SLC', 'AMG GT', 'EQS', 'EQE', 'EQB', 'EQA', 'V-Class', 'Sprinter', 'Maybach S-Class', 'AMG A', 'AMG C', 'AMG E', 'AMG G'],
  'Mercury': ['Grand Marquis', 'Mountaineer', 'Milan', 'Mariner', 'Montego', 'Milan Hybrid'],
  'MG': ['ZS', 'HS', 'RX5', 'RX9', 'GT', '3', '4', '5', '6', '7', 'One', 'T60', 'Cyberster', 'Whale', 'MG5', 'MG7'],
  'MINI': ['Cooper', 'Countryman', 'Clubman', 'Paceman', 'Convertible', 'Hardtop', 'John Cooper Works'],
  'Mitsubishi': ['Outlander', 'Outlander PHEV', 'Eclipse Cross', 'ASX', 'Pajero', 'Pajero Sport', 'L200', 'Lancer', 'Mirage', 'Attrage', 'Xpander', 'Xpander Cross', 'Triton'],
  'Morgan': ['Plus 4', 'Plus 6', 'Roadster', 'Plus 8', 'Aero 8', '3 Wheeler'],
  'Nio': ['ET5', 'ET7', 'ES6', 'ES7', 'ES8', 'EC6', 'EC7', 'ET5 Touring', 'EL8', 'EP9'],
  'Nissan': ['Altima', 'Maxima', 'Sentra', 'Versa', 'Leaf', 'Ariya', 'Rogue', 'Murano', 'Pathfinder', 'Armada', 'Frontier', 'Titan', 'Z', '370Z', '350Z', 'Kicks', 'Juke', 'Qashqai', 'X-Trail', 'Xterra', 'Navara', 'Patrol', 'Sunny', 'Micra', 'Tiida'],
  'Noble': ['M600', 'M500', 'M15'],
  'Omoda': ['C5', 'E5', 'C5 AWD'],
  'Opel': ['Astra', 'Corsa', 'Mokka', 'Grandland', 'Crossland', 'Insignia', 'Zafira', 'Vivaro', 'Combo', 'Adam', 'Meriva', 'Vectra'],
  'Oullim': ['Spirra'],
  'Pagani': ['Huayra', 'Zonda', 'Utopia'],
  'Peugeot': ['208', '308', '508', '2008', '3008', '5008', 'e-2008', 'e-208', 'e-3008', '408', 'Rifter', 'Partner', 'Expert', 'Boxer', 'Traveller'],
  'Polestar': ['2', '3', '4', '5', '6'],
  'Porsche': ['911', 'Cayenne', 'Macan', 'Panamera', 'Taycan', '718 Boxster', '718 Cayman', 'Cayenne Coupe'],
  'Proton': ['Saga', 'Persona', 'Iriz', 'Exora', 'X70', 'X50', 'X90', 'Satria', 'Waja', 'Gen-2', 'Savvy'],
  'Rabdan': ['One'],
  'Ram': ['1500', '2500', '3500', 'ProMaster'],
  'Renault': ['Clio', 'Arkana', 'Captur', 'Austral', 'Koleos', 'Espace', 'Trafic', 'Kangoo', 'Master', 'Zoe', 'Twizy', 'Duster', 'Logan', 'Sandero', 'Symbol', 'Megane', 'Talisman', 'Laguna', 'Fluence', 'Safrane'],
  'Roewe': ['RX5', 'RX5 MAX', 'iMAX8', 'D7', 'D5X', 'Clever', 'i6'],
  'Rolls Royce': ['Phantom', 'Ghost', 'Cullinan', 'Spectre', 'Dawn', 'Wraith', 'Silver Cloud', 'Silver Ghost'],
  'Saab': ['9-3', '9-4X', '9-5', '9-7X'],
  'Seat': ['Leon', 'Ibiza', 'Arona', 'Ateca', 'Tarraco', 'Alhambra', 'Exeo', 'Cordoba', 'Toledo'],
  'Seres': ['SF5', 'SF7', 'M5', 'M7'],
  'Skoda': ['Octavia', 'Superb', 'Kodiaq', 'Karoq', 'Kamiq', 'Scala', 'Fabia', 'Yeti', 'Roomster', 'Rapid', 'Enyaq'],
  'Skywell': ['ET5', 'U75', 'HT-i'],
  'Smart': ['#1', '#3', 'Fortwo', 'Forfour', 'Roadster'],
  'Soueast': ['S06', 'S07', 'S08', 'DX3', 'DX5', 'DX7', 'DX9'],
  'Spyker': ['C8', 'C12', 'D8', 'C16'],
  'Ssangyong': ['Tivoli', 'Korando', 'Rexton', 'Actyon', 'Musso', 'Rodius', 'Kyron'],
  'Subaru': ['Outback', 'Forester', 'Crosstrek', 'Impreza', 'Legacy', 'WRX', 'BRZ', 'Ascent', 'Solterra', 'Tribeca', 'Baja', 'SVX'],
  'Suzuki': ['Swift', 'Baleno', 'Vitara', 'S-Cross', 'Jimny', 'Ignis', 'Celerio', 'Dzire', 'Ertiga', 'XL7', 'Grand Vitara', 'Carry', 'APV', 'Alto', 'Wagon R'],
  'Tank': ['300', '500', '700'],
  'Tata': ['Nexon', 'Punch', 'Harrier', 'Safari', 'Altroz', 'Tiago', 'Tiago EV', 'Punch EV', 'Nexon EV', 'Indica', 'Indigo', 'Sumo', 'Xenon'],
  'Tesla': ['Model S', 'Model 3', 'Model X', 'Model Y', 'Cybertruck', 'Roadster', 'Semi'],
  'Toyota': ['Camry', 'Corolla', 'RAV4', 'Highlander', 'Land Cruiser', '4Runner', 'Tacoma', 'Tundra', 'Sequoia', 'Prius', 'Supra', '86', 'GR86', 'GR Corolla', 'GR Yaris', 'C-HR', 'Corolla Cross', 'Corolla Hatchback', 'Yaris', 'Yaris Sedan', 'Venza', 'Sienna', 'Avalon', 'Crown', 'bZ4X', 'Mirai', 'Hilux', 'Fortuner', 'Innova', 'Urban Cruiser', 'Raize', 'Rush', 'Avanza', 'Hiace', 'Granvia', 'Previa', 'Celica', 'MR2', 'Echo', 'Prius C', 'Prius V'],
  'VinFast': ['VF 8', 'VF 9', 'VF 6', 'VF 7', 'VF 5', 'VF e34'],
  'Volkswagen': ['Golf', 'Passat', 'Tiguan', 'Touareg', 'Polo', 'Jetta', 'Arteon', 'Taos', 'T-Roc', 'Teramont', 'Atlas', 'ID.4', 'ID.5', 'ID.6', 'ID.Buzz', 'Beetle', 'Scirocco', 'Sharan', 'Touran', 'Multivan', 'Caddy', 'Transporter', 'Amarok'],
  'Volvo': ['XC90', 'XC60', 'XC40', 'S90', 'S60', 'V90', 'V60', 'XC70', 'S40', 'S80', 'C30', 'C70', 'EX30', 'EX90', 'EM90'],
  'Voyah': ['Free', 'Free+', 'Dreamer', 'Dreamer PHEV', 'Passion', 'Passion PHEV', 'Courage'],
  'WEY': ['Mocha', 'Coffee 01', 'Coffee 02', 'P8', 'VV6', 'VV7', 'Tank 300', 'Tank 500'],
  'XPeng': ['G3', 'G3i', 'G9', 'P5', 'P7', 'P7i', 'X9', 'Mona M03'],
  'Yangwang': ['U8', 'U9', 'U7'],
  'Zeekr': ['001', 'X', '009', '007', '009光辉版', 'X光辉版'],
  'Zotye': ['T600', 'T700', 'SR9', 'Z100', 'Z300', 'Z500', 'E200']
};

// Sample trims for selected models
export const carTrims: Record<string, Record<string, string[]>> = {
  'Toyota': {
    'Camry': ['LE', 'SE', 'XLE', 'XSE', 'TRD', 'Nightshade'],
    'Corolla': ['L', 'LE', 'SE', 'XLE', 'XSE', 'Hybrid'],
    'RAV4': ['LE', 'XLE', 'XLE Premium', 'Adventure', 'TRD Off-Road', 'Limited', 'Hybrid', 'Prime'],
    'Land Cruiser': ['EXR', 'GXR', 'VXR', 'GR Sport'],
    'Tacoma': ['SR', 'SR5', 'TRD Sport', 'TRD Off-Road', 'Limited', 'TRD Pro'],
    'Tundra': ['SR', 'SR5', 'Limited', 'Platinum', '1794 Edition', 'TRD Pro'],
  },
  'Honda': {
    'Civic': ['LX', 'Sport', 'EX', 'Touring', 'Si', 'Type R'],
    'Accord': ['LX', 'EX', 'Sport', 'Sport-L', 'Touring', 'Hybrid'],
    'CR-V': ['LX', 'EX', 'EX-L', 'Sport', 'Sport-L', 'Touring'],
  },
  'Ford': {
    'F-150': ['XL', 'XLT', 'Lariat', 'King Ranch', 'Platinum', 'Raptor', 'Raptor R', 'Tremor'],
    'Mustang': ['EcoBoost', 'GT', 'Dark Horse', 'Bullitt', 'Shelby GT500', 'Mach 1'],
    'Bronco': ['Base', 'Big Bend', 'Black Diamond', 'Badlands', 'Wildtrak', 'Raptor', 'Everglades'],
  },

  'Lexus': {
    'RX': ['RX 350', 'RX 350 F Sport', 'RX 500h F Sport', 'RX 450h+', 'RX 450h'],
    'ES': ['ES 250', 'ES 300h', 'ES 350', 'F Sport'],
    'NX': ['NX 250', 'NX 350', 'NX 350h', 'NX 450h+', 'F Sport'],
    'IS': ['IS 300', 'IS 350', 'IS 500 F Sport'],
    'GX': ['GX 550', 'GX 550 Overtrail', 'GX 550 Premium+'],
    'LX': ['LX 600', 'LX 600 Premium', 'LX 600 Luxury', 'LX 600 F Sport'],
    'UX': ['UX 200', 'UX 250h', 'UX 300h'],
    'LC': ['LC 500', 'LC 500h', 'LC 500 Convertible', 'F Sport'],
    'LS': ['LS 350', 'LS 500', 'LS 500h', 'F Sport'],
    'RZ': ['RZ 300e', 'RZ 450e', 'RZ 450e F Sport'],
  },
  'Subaru': {
    'Outback': ['Base', 'Premium', 'Onyx Edition', 'Limited', 'Touring', 'Wilderness'],
    'Forester': ['Base', 'Premium', 'Sport', 'Limited', 'Touring', 'Wilderness', 'XT'],
    'Crosstrek': ['Base', 'Premium', 'Sport', 'Limited', 'Wilderness'],
    'Impreza': ['Base', 'Premium', 'Sport', 'Limited', 'WRX', 'WRX STI'],
    'Legacy': ['Base', 'Premium', 'Limited', 'Touring', 'XT'],
    'BRZ': ['Premium', 'Limited', 'tS', 'S'],
    'Solterra': ['Premium', 'Limited', 'Touring'],
  },
  'Volkswagen': {
    'Golf': ['Trendline', 'Comfortline', 'Highline', 'R', 'GTI', 'GTE'],
    'Tiguan': ['Trendline', 'Comfortline', 'Highline', 'R-Line', 'Allspace'],
    'Passat': ['Trendline', 'Comfortline', 'Highline', 'R-Line'],
    'Arteon': ['Elegance', 'R-Line', 'Shooting Brake'],
    'Touareg': ['V6', 'V8', 'R-Line', 'Luxury'],
    'Polo': ['Trendline', 'Comfortline', 'Highline', 'R-Line', 'GTI'],
    'ID.4': ['Pro', 'Pro S', 'GTX', 'Pure'],
    'ID.Buzz': ['Pro', 'Pro S', 'GTX'],
    'Amarok': ['Trendline', 'Highline', 'Panamericana', 'Adventure'],
  },
  'Volvo': {
    'XC90': ['Core', 'Plus', 'Pro', 'Ultimate', 'Recharge'],
    'XC60': ['Core', 'Plus', 'Pro', 'Ultimate', 'Recharge'],
    'XC40': ['Core', 'Plus', 'Pro', 'Ultimate', 'Recharge', 'C40'],
    'S90': ['Core', 'Plus', 'Pro', 'Ultimate', 'Recharge'],
    'S60': ['Core', 'Plus', 'Pro', 'Ultimate', 'Recharge', 'Polestar'],
    'V60': ['Core', 'Plus', 'Pro', 'Ultimate', 'Cross Country', 'Recharge'],
    'V90': ['Core', 'Plus', 'Pro', 'Ultimate', 'Cross Country', 'Recharge'],
    'EX30': ['Core', 'Plus', 'Ultra', 'Twin'],
    'EX90': ['Plus', 'Ultra', 'Twin Performance'],
  },
  'Tesla': {
    'Model 3': ['RWD', 'Long Range', 'Performance', 'Highland'],
    'Model Y': ['RWD', 'Long Range', 'Performance', 'Juniper'],
    'Model S': ['RWD', 'Plaid', 'Plaid+'],
    'Model X': ['RWD', 'Plaid', 'Plaid+'],
    'Cybertruck': ['Single Motor', 'Dual Motor', 'Tri Motor', 'Cyberbeast'],
    'Roadster': ['Base', 'Founders Series'],
    'Semi': ['Day Cab'],
  },
  'Audi': {
    'A3': ['Premium', 'Premium Plus', 'S Line', 'RS 3'],
    'A4': ['Premium', 'Premium Plus', 'Prestige', 'S Line', 'Allroad'],
    'A5': ['Premium', 'Premium Plus', 'Prestige', 'S Line', 'Cabriolet', 'Sportback'],
    'A6': ['Premium', 'Premium Plus', 'Prestige', 'S Line', 'Allroad', 'e-tron'],
    'A7': ['Premium', 'Premium Plus', 'Prestige', 'S Line'],
    'A8': ['Premium', 'Premium Plus', 'Prestige', 'L', 'S8'],
    'Q2': ['Premium', 'Premium Plus', 'S Line', 'RS Q2'],
    'Q3': ['Premium', 'Premium Plus', 'Prestige', 'S Line', 'RS Q3'],
    'Q5': ['Premium', 'Premium Plus', 'Prestige', 'S Line', 'e-tron', 'Sportback'],
    'Q7': ['Premium', 'Premium Plus', 'Prestige', 'S Line', 'e-tron'],
    'Q8': ['Premium', 'Premium Plus', 'Prestige', 'S Line', 'e-tron', 'Sportback'],
    'e-tron': ['Premium', 'Premium Plus', 'Prestige', 'GT', 'Sportback'],
    'RS e-tron GT': ['Base', 'Performance', 'GT'],
    'R8': ['V10', 'V10 Performance', 'Spyder', 'GT'],
    'TT': ['Premium', 'Premium Plus', 'S Line', 'RS'],
  },
  'BMW': {
    '3 Series': ['320i', '330i', '330e', 'M340i', 'M340d', 'M3', 'M3 Competition', 'M3 CS'],
    '4 Series': ['420i', '430i', '440i', 'M440i', 'M4', 'M4 Competition', 'M4 CSL', 'Convertible', 'Gran Coupe'],
    '5 Series': ['520i', '530i', '530e', '540i', 'M550i', 'M5', 'M5 Competition', 'Touring'],
    '7 Series': ['730i', '735i', '740i', '745e', '760i', 'M760e', 'i7'],
    'X1': ['sDrive18i', 'xDrive20i', 'xDrive23i', 'M35i', 'iX1'],
    'X2': ['sDrive20i', 'xDrive20i', 'xDrive25i', 'M35i', 'iX2'],
    'X3': ['xDrive20i', 'xDrive30i', 'xDrive30e', 'M40i', 'xDrive40i', 'M', 'iX3'],
    'X4': ['xDrive20i', 'xDrive30i', 'M40i', 'xDrive40i', 'M', 'Competition'],
    'X5': ['sDrive40i', 'xDrive40i', 'xDrive45e', 'M50i', 'M', 'xDrive50i', 'iX'],
    'X6': ['xDrive30i', 'xDrive40i', 'M50i', 'M', 'Competition', 'xDrive50i'],
    'X7': ['xDrive40i', 'xDrive40d', 'M60i', 'M', 'xDrive50i', 'iX'],
    'Z4': ['sDrive20i', 'sDrive30i', 'M40i', 'M'],
    'M2': ['M2', 'M2 Competition', 'M2 CS'],
    'M3': ['M3', 'M3 Competition', 'M3 Competition xDrive', 'M3 CS'],
    'M4': ['M4', 'M4 Competition', 'M4 Competition xDrive', 'M4 CSL', 'M4 GT4'],
    'M5': ['M5', 'M5 Competition', 'M5 CS', 'M5 Touring'],
    'M8': ['M8', 'M8 Competition', 'M8 Gran Coupe', 'M8 Convertible'],
    'i4': ['eDrive35', 'eDrive40', 'M50', 'M50 xDrive'],
    'i5': ['eDrive40', 'xDrive40', 'M60', 'M60 xDrive', 'M5'],
    'i7': ['eDrive50', 'xDrive60', 'M70', 'xDrive60'],
    'iX': ['xDrive40', 'xDrive50', 'M60', 'M60 xDrive'],
  },
  'Mercedes-Benz': {
    'A-Class': ['A 180', 'A 200', 'A 220', 'A 250', 'A 35', 'A 45'],
    'C-Class': ['C 180', 'C 200', 'C 220', 'C 300', 'C 400', 'AMG C 43', 'AMG C 63', 'AMG C 63 S'],
    'E-Class': ['E 200', 'E 220', 'E 300', 'E 350', 'E 400', 'E 450', 'AMG E 43', 'AMG E 53', 'AMG E 63', 'AMG E 63 S'],
    'S-Class': ['S 350', 'S 400', 'S 450', 'S 500', 'S 560', 'S 580', 'S 600', 'S 650', 'AMG S 63', 'AMG S 65', 'Maybach S 480', 'Maybach S 560', 'Maybach S 680'],
    'GLA': ['GLA 180', 'GLA 200', 'GLA 220', 'GLA 250', 'AMG GLA 35', 'AMG GLA 45'],
    'GLB': ['GLB 180', 'GLB 200', 'GLB 220', 'GLB 250', 'AMG GLB 35', 'AMG GLB 45'],
    'GLC': ['GLC 200', 'GLC 220', 'GLC 300', 'GLC 400', 'GLC 300e', 'GLC 350e', 'AMG GLC 43', 'AMG GLC 63', 'AMG GLC 63 S', 'Coupe'],
    'GLE': ['GLE 300', 'GLE 350', 'GLE 400', 'GLE 450', 'GLE 300e', 'GLE 350e', 'GLE 400e', 'AMG GLE 43', 'AMG GLE 53', 'AMG GLE 63', 'AMG GLE 63 S', 'Coupe'],
    'GLS': ['GLS 400', 'GLS 450', 'GLS 500', 'GLS 580', 'GLS 600', 'GLS 63', 'AMG GLS 63', 'Maybach GLS 480', 'Maybach GLS 600'],
    'G-Class': ['G 350', 'G 400', 'G 500', 'G 550', 'G 63', 'G 65', 'G 550 4x4', 'G 400d'],
    'CLA': ['CLA 180', 'CLA 200', 'CLA 220', 'CLA 250', 'AMG CLA 35', 'AMG CLA 45', 'Shooting Brake'],
    'CLS': ['CLS 300', 'CLS 350', 'CLS 400', 'CLS 450', 'AMG CLS 53', 'AMG CLS 63'],
    'SL': ['SL 280', 'SL 320', 'SL 400', 'SL 450', 'SL 500', 'SL 55', 'SL 63', 'SL 65', 'AMG SL 43', 'AMG SL 55', 'AMG SL 63', 'AMG SL 65'],
    'SLC': ['SLC 180', 'SLC 200', 'SLC 300', 'AMG SLC 43'],
    'EQS': ['EQS 350', 'EQS 450+', 'EQS 500', 'EQS 580 4MATIC', 'EQS 600', 'AMG EQS 53', 'AMG EQS 63', 'SUV'],
    'EQE': ['EQE 300', 'EQE 350+', 'EQE 500 4MATIC', 'AMG EQE 43', 'AMG EQE 53', 'SUV'],
    'EQA': ['EQA 250', 'EQA 300', 'EQA 350'],
    'EQB': ['EQB 250', 'EQB 300', 'EQB 350'],
    'EQC': ['EQC 400'],
    'AMG GT': ['GT', 'GT S', 'GT C', 'GT R', 'GT R Pro', 'GT 4-Door Coupe', 'GT 63', 'GT 63 S', 'Roadster'],
    'V-Class': ['V 220', 'V 250', 'V 300', 'V 300 d', 'Marco Polo', 'EQV'],
    'Sprinter': ['Sprinter 1500', 'Sprinter 2500', 'Sprinter 3500', 'Sprinter 4500'],
  },
  'Mazda': {
    'CX-5': ['Sport', 'Touring', 'Carbon Edition', 'Premium', 'Premium Plus', 'Signature', 'Turbo', '2.5 S', '2.5 S Select', '2.5 S Preferred', '2.5 S Premium', '2.5 S Premium Plus', '2.5 Turbo', '2.5 Turbo Signature'],
    'CX-9': ['Sport', 'Touring', 'Carbon Edition', 'Grand Touring', 'Premium', 'Signature', 'Turbo', 'Carbon Turbo', 'Grand Touring Carbon', 'Premium Carbon'],
    'CX-30': ['Sport', 'Select', 'Preferred', 'Premium', 'Premium Plus', 'Turbo', 'Turbo Premium Plus'],
    'CX-50': ['Base', 'Preferred', 'Premium', 'Premium Plus', 'Turbo', 'Turbo Premium Plus', 'Turbo Meridian Edition'],
    'CX-70': ['Preferred', 'Premium', 'Premium Plus', 'Turbo', 'Turbo Premium Plus'],
    'CX-90': ['Preferred', 'Premium', 'Premium Plus', 'Turbo', 'Turbo Premium Plus', 'Turbo Signature', 'PHEV', 'PHEV Premium Plus'],
    'MAZDA3': ['Sport', 'Select', 'Preferred', 'Premium', '2.5 S', '2.5 S Select', '2.5 S Preferred', '2.5 S Premium', '2.5 Turbo', '2.5 Turbo Premium', 'Hatchback', 'Sedan', 'Carbon Edition'],
    'MAZDA6': ['Sport', 'Touring', 'Grand Touring', 'Grand Touring Reserve', 'Signature', 'Turbo', 'Carbon Edition'],
    'MX-5 Miata': ['Sport', 'Club', 'Grand Touring', 'RF', 'RF Club', 'RF Grand Touring', 'RF GT', 'Miata 100th Anniversary', 'Club Brembo', 'Grand Touring Brembo'],
    'MX-30': ['EV', 'EV Premium Plus', 'EV Carbon Edition', 'R-EV', 'R-EV Premium Plus'],
  },
  'Suzuki': {
    'Swift': ['Motion', 'GL', 'GLX', 'Hybrid', 'Hybrid Plus', 'Hybrid GLX', 'Sport', 'RS'],
    'Baleno': ['GL', 'GLX', 'Delta', 'Zeta', 'Alpha'],
    'Vitara': ['GL', 'GLX', 'S', 'SX', 'Turbo', 'Hybrid', 'AllGrip'],
    'S-Cross': ['GL', 'GLX', 'S', 'SX', 'Hybrid', 'AllGrip'],
    'Jimny': ['JS', 'JL', 'JLX', 'S', 'S AllGrip', 'X', 'X AllGrip', 'Hard Top', 'Soft Top', ' Sierra'],
    'Ertiga': ['GL', 'GLX', 'VXi', 'ZXi', 'ZXi+', 'Sport'],
    'XL7': ['GL', 'GLX', 'Alpha', 'Beta', 'Zeta'],
    'Ignis': ['GL', 'GLX', 'S', 'SX', 'AllGrip'],
    'Celerio': ['GL', 'GLX', 'VXi', 'ZXi'],
    'Dzire': ['LXi', 'VXi', 'ZXi', 'VXi AT', 'ZXi+', 'AMT'],
    'Ciaz': ['GL', 'GLX', 'Delta', 'Alpha', 'S', 'SX'],
    'Carry': ['Std', 'PU', 'Cabin', 'Ladder Rack'],
  },
  'Peugeot': {
    '208': ['Active', 'Active Premium', 'Allure', 'Allure Premium', 'GT', 'GT Premium', 'e-208', 'e-208 GT', 'GTi'],
    '308': ['Active', 'Allure', 'GT', 'GT Premium', 'SW', 'SW GT', 'Estate', 'PHEV', 'e-308'],
    '3008': ['Active', 'Active Premium', 'Allure', 'Allure Premium', 'GT', 'GT Premium', 'Hybrid', 'PHEV', 'e-3008'],
    '5008': ['Active', 'Active Premium', 'Allure', 'Allure Premium', 'GT', 'GT Premium', 'Hybrid', 'PHEV', 'e-5008'],
    '508': ['Active', 'Allure', 'GT', 'GT Premium', 'SW', 'SW GT', 'Peugeot Sport Engineered', 'PHEV', 'e-508'],
    '2008': ['Active', 'Allure', 'GT', 'e-2008', 'e-2008 GT'],
    '408': ['Allure', 'GT', 'Business', 'GT Exclusive', 'PHEV'],
    'Rifter': ['Active', 'Allure', 'GT', 'Outdoor', 'Long', 'Standard'],
    'Partner': ['L1', 'L2', 'L3', 'Pro', 'Asphalt', 'Offroad'],
    'Boxer': ['L1', 'L2', 'L3', 'L4', 'Pro', 'Window', 'Crew Cab', 'Minibus'],
    'e-Rifter': ['Allure', 'GT', 'Long'],
    'e-Expert': ['Pro', 'Asphalt', 'Long', 'Crew Cab'],
  },
  'Skoda': {
    'Octavia': ['SE', 'SE Technology', 'SE L', 'Sportline', 'vRS', 'Monte Carlo', 'Scout', 'Style', ' Laurin & Klement'],
    'Superb': ['SE', 'SE Technology', 'SE L', 'Sportline', 'vRS', 'Scout', 'Style', ' Laurin & Klement', 'L&K Executive', 'L&K Black'],
    'Kodiaq': ['SE', 'SE Technology', 'SE L', 'Sportline', 'vRS', 'Scout', 'Style', ' Laurin & Klement', 'L&K Black', 'L&K Executive'],
    'Karoq': ['SE', 'SE Technology', 'SE L', 'Sportline', 'Scout', 'Style'],
    'Kamiq': ['SE', 'SE Technology', 'SE L', 'Sportline', 'Monte Carlo'],
    'Scala': ['SE', 'SE Technology', 'SE L', 'Sportline', 'Monte Carlo'],
    'Fabia': ['S', 'SE', 'SE L', 'Monte Carlo', 'Colour Edition'],
    'Yeti': ['S', 'SE', 'SE L', 'Outdoor', 'L&K'],
    'Enyaq': ['60', '80', '80x', 'vRS', 'Coupé', 'Coupé vRS', 'RS', 'iV', 'Coupé iV'],
    'Elroq': ['Selection', 'Style', 'Sportline', 'vRS'],
    'Kushaq': ['Active', 'Ambition', 'Style', 'Monte Carlo', 'Sportline'],
  },
  'Renault': {
    'Clio': ['Life', 'Zen', 'Intens', 'RS Line', 'R.S. 280', 'R.S. 300', 'E-Tech', 'Hybrid'],
    'Arkana': ['Life', 'Zen', 'Intens', 'RS Line', 'R.S. Line', 'E-Tech', 'Hybrid'],
    'Captur': ['Life', 'Zen', 'Intens', 'RS Line', 'S-Edition', 'E-Tech', 'Hybrid'],
    'Austral': ['Evolution', 'Techno', 'Esprit Alpine', 'Iconic', 'R.S. Line', 'E-Tech', 'Hybrid'],
    'Koleos': ['Life', 'Zen', 'Intens', 'S-Edition', 'Initiale Paris'],
    'Espace': ['Life', 'Zen', 'Intens', 'E-Tech', 'Hybrid', 'E-Tech Hybrid'],
    'Trafic': ['L1H1', 'L2H1', 'L2H2', 'L3H2', 'Passenger', 'Combi', 'Pro', 'Sliding Side Door'],
    'Kangoo': ['L1', 'L2', 'Passenger', 'Pro', 'Z.E.', 'Electric', 'Maxi'],
    'Master': ['L2H1', 'L2H2', 'L3H2', 'L3H3', 'Platform Cab', 'Bus', 'Tow Truck', 'Box', 'Chassis'],
    'Zoe': ['Life', 'Zen', 'Intens', 'R.S. Line', 'GT', 'E-Tech', 'Iconic'],
    'Megane': ['Life', 'Zen', 'Intens', 'RS Line', 'R.S. 280', 'R.S. 300', 'E-Tech', 'Hybrid', 'Sedan'],
    'Talisman': ['Life', 'Zen', 'Intens', 'Initiale Paris', 'Luxe', 'S-Edition', 'E-Tech'],
    'Duster': ['Access', 'Climber', 'Laureate', 'Prestige', 'SE', 'Techroad'],
    'Logan': ['Access', 'Sandero Stepway', 'Prestige', 'Laureate'],
    'Sandero': ['Access', 'Stepway', 'Prestige', 'Bi-Fuel', 'TCE'],
  },
  'Opel': {
    'Corsa': ['Corsa', 'Corsa-e', 'GS', 'GS Line', 'Ultimate', 'GSi', 'Racing', 'Electric'],
    'Astra': ['Edition', 'Elegance', 'GS Line', 'Ultimate', 'GSi', 'Plug-in Hybrid', 'Electric', 'Sports Tourer'],
    'Mokka': ['Edition', 'Elegance', 'GS Line', 'Ultimate', 'GS', 'Electric', 'e-Mokka'],
    'Grandland': ['Edition', 'Elegance', 'GS Line', 'Ultimate', 'Plug-in Hybrid', 'X', 'Electric'],
    'Crossland': ['Edition', 'Elegance', 'GS Line', 'Ultimate'],
    'Insignia': ['Edition', 'Elegance', 'GS Line', 'Ultimate', 'GSi', 'Country Tourer', 'Sports Tourer'],
    'Zafira': ['Life', 'Elegance', 'GS Line', 'Ultimate', 'Family', 'Tourer'],
    'Vivaro': ['Combi', 'Life', 'Cargo', 'Pro', 'Electric', 'e-Vivaro'],
    'Combo': ['Life', 'Cargo', 'Pro', 'Electric', 'e-Combo'],
    'Movano': ['L1H1', 'L2H1', 'L2H2', 'L3H2', 'Chassis Cab', 'Platform Cab', 'Bus'],
    'Meriva': ['Expression', 'Innovation', 'Cosmo', 'OPC'],
    'Adam': ['Jam', 'S', 'Rocks', 'Unlimited', 'Sisters'],
    'Karl': ['Jam', 'Essentia', 'Rocks', 'Viva'],
  },
  'Citroen': {
    'C3': ['Live', 'Feel', 'Shine', 'C-Series', 'Electric', 'e-C3'],
    'C4': ['Live', 'Feel', 'Shine', 'C-Series', 'XTR', 'Electric', 'e-C4'],
    'C5 X': ['Live', 'Feel', 'Shine', 'C-Series', 'XTR', 'Plug-in Hybrid', 'Shine Plus'],
    'C5 Aircross': ['Live', 'Feel', 'Shine', 'C-Series', 'XTR', 'Shine Plus', 'Plug-in Hybrid'],
    'C3 Aircross': ['Live', 'Feel', 'Shine', 'C-Series', 'XTR'],
    'Berlingo': ['X', 'Feel', 'Shine', 'Driver', 'Worker', 'M', 'XL', 'Electric', 'e-Berlingo'],
    'Dispatch': ['M', 'L', 'XL', 'Worker', 'Pro', 'Electric', 'e-Dispatch'],
    'Jumpy': ['M', 'L', 'XL', 'Worker', 'Pro', 'Electric', 'e-Jumpy'],
    'C-Elysee': ['Seduction', 'Grace', 'Exclusive'],
    'C1': ['Touch', 'Feel', 'Shine', 'Airscape'],
    'C5': ['Exclusive', 'Prestige', 'Tourer'],
    'DS3': ['Chic', 'So Chic', 'Ultra Chic', 'Performance Line', 'Crossback'],
    'DS4': ['Elegance', 'Performance Line', 'Rivoli', 'Trocadero', 'Esprit de Voyage'],
    'DS7': ['Performance Line', 'Rivoli', 'Opera', 'E-Tense', 'Crossback'],
  },
  'Alfa Romeo': {
    'Giulia': ['Giulia', 'Super', 'Ti', 'Veloce', 'Quadrifoglio', 'Pole Position', 'Estrema', 'Competizione'],
    'Stelvio': ['Stelvio', 'Super', 'Ti', 'Veloce', 'Quadrifoglio', 'Estrema', 'Competizione'],
    'Tonale': ['Tonale', 'Sprint', 'Ti', 'Veloce', 'Estrema', 'Quadrifoglio', 'PHEV', 'Alfa Romeo Q4'],
    '4C': ['4C', '4C Spider', 'Competizione', 'Launch Edition'],
    'Giulietta': ['Giulietta', 'Super', 'Veloce', 'Quadrifoglio', 'TCT'],
    'Mito': ['Mito', 'Super', 'Quadrifoglio', 'TCT'],
    'Stelvio Quadrifoglio': ['Quadrifoglio', 'NRing', 'Estrema'],
    'Giulia Quadrifoglio': ['Quadrifoglio', 'NRing', 'Estrema', 'Pole Position'],
    'Spider': ['Spider', 'Duetto', '4C Spider'],
    '159': ['159', 'TI', 'Veloce', 'Sport'],
    '156': ['156', '156 GTA', 'Sportwagon'],
  },
  'Acura': {
    'MDX': ['Base', 'Technology', 'A-Spec', 'Advance', 'PMC Edition', 'Type S', 'Type S Advance'],
    'TLX': ['Base', 'Technology', 'A-Spec', 'Advance', 'Type S', 'Type S Advance', 'PMC Edition'],
    'RDX': ['Base', 'Technology', 'A-Spec', 'Advance', 'PMC Edition'],
    'NSX': ['NSX', 'NSX GT3', 'NSX SA', 'NSX SC'],
    'ILX': ['Base', 'Premium', 'A-Spec', 'Technology'],
    'Integra': ['Base', 'A-Spec', 'Technology', 'Limited'],
    'RLX': ['Base', 'Technology', 'Advance', 'Sport Hybrid'],
    'ZDX': ['Base', 'A-Spec', 'Advance', 'Type S'],
    'TSX': ['Base', 'Premium', 'Technology', 'V6'],
    'RL': ['Base', 'Technology', 'Advance'],
  },
  'Genesis': {
    'G70': ['Advanced', 'Prestige', 'Sport', 'Sport Advanced', 'Dawn', 'Shooting Brake', 'Electrified'],
    'G80': ['Advanced', 'Prestige', 'Luxury', 'Sport', 'Electrified', 'Electrified Sport'],
    'G90': ['Advanced', 'Luxury', 'Premium', 'Signature', 'LWB', 'Electrified'],
    'GV60': ['Advanced', 'Performance', 'Performance Plus', 'Magma', 'N Line'],
    'GV70': ['Advanced', 'Prestige', 'Sport', 'Sport Prestige', 'Electrified', 'Electrified Sport', 'N Line'],
    'GV80': ['Advanced', 'Prestige', 'Luxury', 'Signature', 'N Line', '3.5T Sport'],
    'Electrified G80': ['Electrified G80', 'Electrified G80 Sport'],
    'Electrified GV70': ['Electrified GV70', 'Electrified GV70 Sport'],
    'G90 LWB': ['LWB', 'LWB Signature', 'LWB Black Label'],
  },
  'Jaguar': {
    'F-Pace': ['P250', 'P300', 'P340', 'P400', 'P400e', 'R-Dynamic S', 'R-Dynamic SE', 'R-Dynamic HSE', 'SVR', 'SVR Carbon Edition'],
    'E-Pace': ['P200', 'P250', 'P300', 'R-Dynamic S', 'R-Dynamic SE', 'R-Dynamic HSE', '300 Sport'],
    'I-Pace': ['S', 'SE', 'HSE', '400 Sport', 'SV', 'SV 400 Sport', 'Carpathian Edition'],
    'F-Type': ['P300', 'P450', 'P575', 'R-Dynamic', 'R', 'SVR', 'Convertible', 'Coupe', 'Heritage 60 Edition'],
    'XE': ['P200', 'P250', 'P300', 'R-Dynamic S', 'R-Dynamic SE', 'R-Dynamic HSE', '300 Sport', 'Project 7'],
    'XF': ['P200', 'P250', 'P300', 'R-Dynamic S', 'R-Dynamic SE', 'R-Dynamic HSE', 'Sportbrake', 'SWB', 'LWB'],
    'XJ': ['XJ50', 'XJR', 'XJL', 'XJL Portfolio', 'XJL Supersport', 'XFR', 'XFR-S'],
    'XK': ['XK', 'XKR', 'XKR-S', 'XKR Portfolio', 'GT', 'GT Signature'],
    'I-Pace eTrophy': ['eTrophy', 'I-Pace eTrophy'],
  },
  'Ineos': {
    'Grenadier': ['Fieldmaster', 'Trialmaster', 'Quartermaster', '72-10 Limited Edition', 'Wagon', 'Station Wagon'],
    'Quartermaster': ['Fieldmaster', 'Trialmaster', 'Quartermaster', 'Pickup', 'Crew Cab'],
    'Grenadier 1924': ['1924 Edition', 'Fieldmaster 1924', 'Trialmaster 1924'],
  },
  'Denza': {
    'D9': ['DM-i', 'EV', 'PHEV', 'Premium', 'Luxury', '4WD'],
    'N7': ['RWD', 'AWD', 'Performance', 'Long Range'],
    'N9': ['DM-i', 'EV', 'PHEV', '4WD', 'Luxury'],
    'Z9': ['EV', 'GT', 'Performance', 'Long Range'],
    'Z9 GT': ['GT', 'PHEV', 'Performance', 'Huntsman'],
    'B5': ['DM-i', 'AWD', 'Premium'],
    'B8': ['DM-i', 'AWD', 'Premium', 'Luxury'],
  },
  'Omoda': {
    'C5': ['Comfort', 'Luxury', 'Premium', 'Sport', 'AWD', '2.0T', '1.6T'],
    'E5': ['Comfort', 'Luxury', 'Premium', 'Long Range', 'AWD'],
    'C5 AWD': ['AWD', 'Premium AWD', 'Sport AWD'],
  },
  'Jaecoo': {
    'J5': ['Comfort', 'Luxury', 'Premium', 'AWD'],
    'J7': ['Comfort', 'Luxury', 'Premium', 'AWD', 'SHS', 'PHEV'],
    'J7 SHS': ['SHS', 'Premium SHS', 'AWD SHS'],
    'J8': ['Luxury', 'Premium', 'AWD', 'PHEV', '4WD'],
  },
  'Jetour': {
    'X70': ['Comfort', 'Luxury', 'Premium', 'AWD'],
    'X70 Plus': ['Comfort', 'Luxury', 'Premium', 'AWD', '7-seater'],
    'X90': ['Comfort', 'Luxury', 'Premium', 'AWD', '7-seater'],
    'X90 Plus': ['Comfort', 'Luxury', 'Premium', 'AWD', '7-seater'],
    'Dashing': ['Comfort', 'Luxury', 'Premium', 'AWD', 'Sport'],
    'T1': ['Comfort', 'Luxury', 'Premium', 'AWD', 'Off-road'],
    'T2': ['Comfort', 'Luxury', 'Premium', 'AWD', 'i-DM', 'Off-road'],
    'G700': ['Luxury', 'Premium', 'AWD', '7-seater', 'LWB'],
  },
  'Exeed': {
    'VX': ['Comfort', 'Luxury', 'Premium', 'AWD', '7-seater'],
    'TXL': ['Comfort', 'Luxury', 'Premium', 'AWD', '7-seater'],
    'LX': ['Comfort', 'Luxury', 'Premium', 'AWD'],
    'RX': ['Comfort', 'Luxury', 'Premium', 'AWD', 'PHEV'],
    'ES': ['Comfort', 'Luxury', 'Premium', 'EV'],
    'ET': ['Comfort', 'Luxury', 'Premium', 'AWD', 'EV'],
    'TXL FL': ['FL', 'Premium FL', 'AWD FL'],
  },
  'Deepal': {
    'S07': ['RWD', 'AWD', 'Long Range', 'Performance'],
    'S05': ['RWD', 'AWD', 'Long Range'],
    'L07': ['RWD', 'AWD', 'Long Range', 'Performance'],
    'S09': ['AWD', 'Long Range', 'Performance', '7-seater'],
    'G318': ['RWD', 'AWD', 'Off-road', 'Long Range'],
  },
  // CHINESE BRANDS
  'Changan': {
    'CS75 Plus': ['Comfort', 'Luxury', 'Premium', 'Premium+', 'Ultra', '2.0T', '1.5T'],
    'CS55 Plus': ['Comfort', 'Luxury', 'Premium', 'Premium+'],
    'CS35 Plus': ['Comfort', 'Luxury', 'Premium'],
    'CS85': ['Comfort', 'Luxury', 'Premium', 'Premium+'],
    'CS95': ['Comfort', 'Luxury', 'Premium', 'Premium+', '4WD'],
    'UNI-K': ['Comfort', 'Luxury', 'Premium', 'Premium+', 'AWD'],
    'UNI-T': ['Comfort', 'Luxury', 'Premium', 'Premium+'],
    'UNI-V': ['Comfort', 'Luxury', 'Premium', 'Premium+', 'GT'],
    'Alsvin': ['Comfort', 'Luxury', 'Premium'],
    'Eado': ['Comfort', 'Luxury', 'Premium'],
    'Hunter': ['Comfort', 'Luxury', 'Premium', '4WD'],
    'Lumin': ['Comfort', 'Luxury', 'Premium', 'EV'],
  },
  'Chery': {
    'Tiggo 8 Pro': ['Aspire', 'Summit', 'Premium', 'Luxury', '7-seater'],
    'Tiggo 8': ['Aspire', 'Summit', 'Premium', 'Luxury', '7-seater'],
    'Tiggo 7 Pro': ['Comfort', 'Luxury', 'Premium', 'Premium+'],
    'Tiggo 7': ['Comfort', 'Luxury', 'Premium'],
    'Tiggo 4 Pro': ['Comfort', 'Luxury', 'Premium'],
    'Tiggo 4': ['Comfort', 'Luxury', 'Premium'],
    'Tiggo 3': ['Comfort', 'Luxury', 'Premium'],
    'Arrizo 8': ['Comfort', 'Luxury', 'Premium'],
    'Arrizo 5': ['Comfort', 'Luxury', 'Premium'],
    'QQ': ['Comfort', 'Luxury', 'EV'],
  },
  'GAC': {
    'GS4': ['Comfort', 'Luxury', 'Premium', 'GT'],
    'GS5': ['Comfort', 'Luxury', 'Premium'],
    'GS7': ['Comfort', 'Luxury', 'Premium', '7-seater'],
    'GS8': ['Comfort', 'Luxury', 'Premium', 'Premium+', '7-seater'],
    'GA4': ['Comfort', 'Luxury', 'Premium'],
    'GA6': ['Comfort', 'Luxury', 'Premium'],
    'GA8': ['Comfort', 'Luxury', 'Premium'],
    'Aion Y': ['Comfort', 'Luxury', 'Premium', 'Plus', 'EV'],
    'Aion V': ['Comfort', 'Luxury', 'Premium', 'Plus', 'EV'],
    'Aion S': ['Comfort', 'Luxury', 'Premium', 'Plus', 'EV'],
    'Aion LX': ['Comfort', 'Luxury', 'Premium', 'Plus', 'EV'],
    'Emkoo': ['Comfort', 'Luxury', 'Premium'],
    'Empow': ['Comfort', 'Luxury', 'Premium', 'GT'],
    'M8': ['Comfort', 'Luxury', 'Premium', 'Premium+', '7-seater'],
  },
  'Geely': {
    'Coolray': ['Comfort', 'Luxury', 'Premium', 'Sport'],
    'Monjaro': ['Comfort', 'Luxury', 'Premium', 'Premium+'],
    'Tugella': ['Comfort', 'Luxury', 'Premium', 'Sport'],
    'Emgrand': ['Comfort', 'Luxury', 'Premium'],
    'Okavango': ['Comfort', 'Luxury', 'Premium', '7-seater'],
    'Azkarra': ['Comfort', 'Luxury', 'Premium'],
    'Geometry C': ['Comfort', 'Luxury', 'Premium', 'EV'],
    'Geometry E': ['Comfort', 'Luxury', 'EV'],
    'Icon': ['Comfort', 'Luxury', 'Premium', 'EV'],
    'Starray': ['Comfort', 'Luxury', 'Premium'],
    'Preface': ['Comfort', 'Luxury', 'Premium'],
    'Xingyue': ['Comfort', 'Luxury', 'Premium', 'Sport'],
    'Galaxy': ['Comfort', 'Luxury', 'Premium', 'EV'],
  },
  'Haval': {
    'H6': ['Comfort', 'Luxury', 'Premium', 'Premium+', 'GT'],
    'H6 GT': ['Comfort', 'Luxury', 'Premium', 'GT'],
    'Jolion': ['Comfort', 'Luxury', 'Premium', 'Premium+'],
    'Dargo': ['Comfort', 'Luxury', 'Premium', 'Premium+', '4WD'],
    'H9': ['Comfort', 'Luxury', 'Premium', 'Premium+', '4WD'],
    'M6': ['Comfort', 'Luxury', 'Premium'],
    'Tank 300': ['Comfort', 'Luxury', 'Premium', 'Premium+', '4WD', 'Urban'],
    'Tank 500': ['Comfort', 'Luxury', 'Premium', 'Premium+', '4WD'],
  },
  'Hongqi': {
    'H9': ['Comfort', 'Luxury', 'Premium', 'Premium+'],
    'HS5': ['Comfort', 'Luxury', 'Premium', 'Premium+'],
    'HS7': ['Comfort', 'Luxury', 'Premium', 'Premium+', '4WD'],
    'E-HS9': ['Comfort', 'Luxury', 'Premium', 'Premium+', 'EV'],
    'H5': ['Comfort', 'Luxury', 'Premium'],
    'LS5': ['Comfort', 'Luxury', 'Premium'],
    'LS7': ['Comfort', 'Luxury', 'Premium', 'Premium+'],
    'HQ9': ['Comfort', 'Luxury', 'Premium', 'Premium+', '7-seater'],
  },
  'Nio': {
    'ET7': ['Comfort', 'Luxury', 'Premium', 'Signature', 'EV'],
    'ET5': ['Comfort', 'Luxury', 'Premium', 'EV'],
    'ES6': ['Comfort', 'Luxury', 'Premium', 'Signature', 'EV'],
    'ES7': ['Comfort', 'Luxury', 'Premium', 'Signature', 'EV'],
    'ES8': ['Comfort', 'Luxury', 'Premium', 'Signature', '7-seater', 'EV'],
    'EC6': ['Comfort', 'Luxury', 'Premium', 'EV'],
    'EC7': ['Comfort', 'Luxury', 'Premium', 'Signature', 'EV'],
    'ET9': ['Comfort', 'Luxury', 'Premium', 'Signature', 'EV'],
  },
  'XPeng': {
    'P7': ['Comfort', 'Luxury', 'Premium', 'Performance', 'EV', 'Wing'],
    'P5': ['Comfort', 'Luxury', 'Premium', 'EV'],
    'G3': ['Comfort', 'Luxury', 'Premium', 'EV'],
    'G6': ['Comfort', 'Luxury', 'Premium', 'Performance', 'EV'],
    'G9': ['Comfort', 'Luxury', 'Premium', 'Performance', 'EV'],
    'X9': ['Comfort', 'Luxury', 'Premium', 'Performance', '7-seater', 'EV'],
  },
  'Zeekr': {
    '001': ['Comfort', 'Luxury', 'Premium', 'Performance', 'EV', 'FR'],
    'X': ['Comfort', 'Luxury', 'Premium', 'Performance', 'EV'],
    '009': ['Comfort', 'Luxury', 'Premium', 'Performance', 'EV', 'LWB'],
    '007': ['Comfort', 'Luxury', 'Premium', 'Performance', 'EV'],
    '001 FR': ['FR', 'Performance', 'Track', 'EV'],
  },
  'Voyah': {
    'Free': ['Comfort', 'Luxury', 'Premium', 'EV', 'PHEV'],
    'Dream': ['Comfort', 'Luxury', 'Premium', 'EV', 'PHEV', '7-seater'],
    'Passion': ['Comfort', 'Luxury', 'Premium', 'EV'],
    '追光': ['Comfort', 'Luxury', 'Premium', 'EV', 'PHEV'],
  },
  'WEY': {
    'Mocha': ['Comfort', 'Luxury', 'Premium', 'PHEV', '4WD'],
    'Kunlun': ['Comfort', 'Luxury', 'Premium', 'PHEV', '4WD'],
    'Pegasus': ['Comfort', 'Luxury', 'Premium', 'PHEV'],
    'Tank 300': ['Comfort', 'Luxury', 'Premium', '4WD'],
    'Shandong': ['Comfort', 'Luxury', 'Premium', 'PHEV'],
  },
  'Tank': {
    '300': ['Comfort', 'Luxury', 'Premium', 'Premium+', '4WD', 'Urban', 'Heritage'],
    '500': ['Comfort', 'Luxury', 'Premium', 'Premium+', '4WD', '7-seater'],
    '400': ['Comfort', 'Luxury', 'Premium', '4WD'],
    '700': ['Comfort', 'Luxury', 'Premium', '4WD'],
  },
  'BAIC': {
    'BJ40': ['Comfort', 'Luxury', 'Premium', '4WD', 'Off-road'],
    'BJ60': ['Comfort', 'Luxury', 'Premium', '4WD', '7-seater'],
    'BJ80': ['Comfort', 'Luxury', 'Premium', '4WD'],
    'X55': ['Comfort', 'Luxury', 'Premium'],
    'X75': ['Comfort', 'Luxury', 'Premium'],
    'U5': ['Comfort', 'Luxury', 'Premium'],
    'EU5': ['Comfort', 'Luxury', 'Premium', 'EV'],
  },
  'Great Wall': {
    'Wingle 5': ['Comfort', 'Luxury', '4WD', 'Pickup'],
    'Wingle 6': ['Comfort', 'Luxury', '4WD', 'Pickup'],
    'Wingle 7': ['Comfort', 'Luxury', '4WD', 'Pickup'],
    'Poer': ['Comfort', 'Luxury', 'Premium', '4WD', 'Pickup'],
    'King Kong Poer': ['Comfort', 'Luxury', '4WD', 'Pickup'],
    'Florid': ['Comfort', 'Luxury', 'EV'],
    'Hover': ['Comfort', 'Luxury', '4WD'],
  },
  'JAC': {
    'JS3': ['Comfort', 'Luxury', 'Premium'],
    'JS4': ['Comfort', 'Luxury', 'Premium'],
    'JS5': ['Comfort', 'Luxury', 'Premium'],
    'JS6': ['Comfort', 'Luxury', 'Premium'],
    'J7': ['Comfort', 'Luxury', 'Premium'],
    'E30X': ['Comfort', 'Luxury', 'EV'],
    'T8': ['Comfort', 'Luxury', '4WD', 'Pickup'],
  },
  'Li Auto': {
    'L9': ['Pro', 'Max', 'Ultra', '7-seater', 'EREV'],
    'L8': ['Pro', 'Max', 'Air', '6-seater', 'EREV'],
    'L7': ['Pro', 'Max', 'Air', '5-seater', 'EREV'],
    'L6': ['Pro', 'Max', '5-seater', 'EREV'],
    'MEGA': ['Max', 'Ultra', '7-seater', 'EV'],
  },
  'Avatr': {
    '11': ['Comfort', 'Luxury', 'Premium', 'AWD', 'EV'],
    '12': ['Comfort', 'Luxury', 'Premium', 'AWD', 'EV'],
    '07': ['Comfort', 'Luxury', 'Premium', 'AWD', 'EV'],
  },
  'Fangchengbao': {
    'Bao 5': ['Comfort', 'Luxury', 'Premium', '4WD', 'Off-road'],
    'Bao 8': ['Comfort', 'Luxury', 'Premium', '4WD', 'Off-road'],
    'Leopard 3': ['Comfort', 'Luxury', 'Premium', '4WD', 'Off-road'],
    'Leopard 5': ['Comfort', 'Luxury', 'Premium', '4WD', 'Off-road'],
    'Leopard 7': ['Comfort', 'Luxury', 'Premium', '4WD', 'Off-road'],
  },
  'Leapmotor': {
    'C11': ['Comfort', 'Luxury', 'Premium', 'EV', 'PHEV'],
    'C01': ['Comfort', 'Luxury', 'Premium', 'EV'],
    'T03': ['Comfort', 'Luxury', 'EV'],
    'B10': ['Comfort', 'Luxury', 'Premium', 'EV'],
  },
  'Hyptec': {
    'HT': ['Comfort', 'Luxury', 'Premium', 'EV'],
    'HL': ['Comfort', 'Luxury', 'Premium', 'EV'],
    'HiPhi': ['Comfort', 'Luxury', 'Premium', 'EV', '4WD'],
  },
  'Yangwang': {
    'U8': ['Premium', 'Luxury', 'Off-road', 'EV', '4WD'],
    'U9': ['Premium', 'Luxury', 'Sports', 'EV'],
  },
  // LUXURY & SPORTS CARS
  'Ferrari': {
    '296 GTB': ['Base', 'Assetto Fiorano', 'GTB', 'GTS', 'PHEV'],
    '296 GTS': ['Base', 'Assetto Fiorano', 'GTS'],
    'SF90 Stradale': ['Base', 'Assetto Fiorano', 'PHEV', '4WD'],
    'SF90 Spider': ['Base', 'Assetto Fiorano', 'PHEV', '4WD'],
    '812 Competizione': ['Base', 'Competizione', 'Competizione Aperta', 'Superfast'],
    '812 Superfast': ['Base', 'Superfast', 'GTS', 'Omologata'],
    'Roma': ['Base', 'Roma', 'DCT', 'Coupé'],
    'Portofino M': ['Base', 'Portofino', 'Cabriolet'],
    'Purosangue': ['Base', 'Purosangue', 'V12', '4WD', '4-seater'],
    'F8 Tributo': ['Base', 'Tributo', 'Spider', 'RWD'],
    'F8 Spider': ['Base', 'Spider', 'RWD'],
    '488 GTB': ['Base', 'GTB', 'Pista', 'Pista Spider', 'RWD'],
    '488 Spider': ['Base', 'Spider', 'Pista', 'Pista Spider'],
    '458 Italia': ['Base', 'Italia', 'Spider', 'Speciale', 'Speciale A'],
    '458 Spider': ['Base', 'Spider', 'Speciale', 'Speciale A'],
    '360 Modena': ['Base', 'Modena', 'Spider', 'Challenge Stradale', 'F1'],
    'California': ['Base', 'California', 'T', 'Handling Speciale'],
    'FF': ['Base', 'FF', 'GTC4Lusso'],
    'GTC4Lusso': ['Base', 'GTC4Lusso', 'T', 'PHEV'],
    'LaFerrari': ['Base', 'LaFerrari', 'Aperta', 'FXX-K', 'XX'],
    'Monza SP1': ['Base', 'SP1', 'SP2', 'Barchetta'],
    'Daytona SP3': ['Base', 'SP3', 'Icona'],
    '12Cilindri': ['Base', 'Cilindri', 'Spider'],
  },
  'Lamborghini': {
    'Revuelto': ['Base', 'Revuelto', 'PHEV', 'AWD', 'Coupé'],
    'Huracan': ['EVO', 'EVO RWD', 'EVO Spyder', 'EVO RWD Spyder', 'Performante', 'Performante Spyder', 'STO', 'Tecnica', 'Stereotype'],
    'Huracan Sterrato': ['Sterrato', 'All-Terrain', 'Off-road'],
    'Aventador': ['LP 700-4', 'LP 750-4', 'LP 780-4', 'Ultimae', 'S', 'SVJ', 'SVJ Roadster', 'Roadster', 'Coupé'],
    'Urus': ['Base', 'S', 'Performante', 'SE', 'PHEV', 'Graphite Edition', 'Pearl Capsule', 'Carbon Edition'],
    'Gallardo': ['LP 560-4', 'LP 570-4', 'LP 570-4 Spyder', 'Superleggera', 'Tricolore', 'Balboni'],
    'Murcielago': ['LP 640', 'LP 670-4', 'LP 670-4 SV', 'Roadster', 'Coupé'],
    'Diablo': ['VT', 'VT Roadster', '6.0', 'GT', 'SV', 'SV Roadster', 'VT 6.0'],
    'Countach': ['LPI 800-4', 'Countach', 'Anniversary'],
    'Veneno': ['Roadster', 'Coupé', 'Roadster LP 750-4'],
  },
  'McLaren': {
    '750S': ['Coupe', 'Spider', 'LT', 'Performance', 'Carbon Series'],
    '720S': ['Coupe', 'Spider', 'GT', 'Performance', 'Luxury', 'Track Pack'],
    '765LT': ['LT', 'Spider', 'Track', 'Carbon Series'],
    'Artura': ['Base', 'Performance', 'GT', 'Spider', 'PHEV'],
    'GT': ['GT', 'Luxury', 'PHEV'],
    '570S': ['Coupe', 'Spider', 'GT', 'S', 'Track Pack'],
    '570GT': ['GT', 'GT Sport', 'Track Pack'],
    '600LT': ['LT', 'Spider', 'Track', 'Carbon Series'],
    '620R': ['R', 'GT3', 'Road Car'],
    '675LT': ['LT', 'Spider', 'Carbon Series', 'MSO'],
    '720S Spider': ['Spider', 'Performance', 'Luxury'],
    'P1': ['P1', 'GTR', 'XP', 'LM'],
    'Senna': ['Senna', 'GTR', 'XP', 'LM', 'Alloy'],
    'Speedtail': ['Speedtail', 'Hyper-GT', 'OM'],
    'Elva': ['Elva', 'MSO', 'Front Splitter', 'Windscreen'],
    'GT2 RS': ['GT2 RS', 'Clubsport', 'Track'],
    'MP4-12C': ['Base', 'Spider', 'GT3', 'Track'],
  },
  'Porsche': {
    '911': ['Carrera', 'Carrera S', 'Carrera 4S', 'Carrera GTS', 'Carrera 4 GTS', 'Turbo', 'Turbo S', 'GT3', 'GT3 RS', 'GT3 GT', 'Targa', 'Targa 4', 'Targa 4S', 'Speedster', 'Dakar', 'Singer'],
    '911 GT3 RS': ['GT3 RS', 'Weissach', 'Clubsport', 'Track'],
    '911 Turbo': ['Turbo', 'Turbo S', 'Turbo Cabriolet', 'Turbo S Cabriolet', 'Exclusive', 'Sport Chrono'],
    '911 Dakar': ['Dakar', 'Rallye', 'Off-road'],
    'Cayenne': ['Cayenne', 'Cayenne S', 'Cayenne GTS', 'Cayenne Turbo', 'Cayenne Turbo GT', 'Cayenne E-Hybrid', 'Cayenne Coupe', 'Cayenne Turbo Coupe'],
    'Macan': ['Macan', 'Macan S', 'Macan GTS', 'Macan Turbo', 'Macan Electric', 'GTS'],
    'Panamera': ['Panamera', 'Panamera 4', 'Panamera 4S', 'Panamera 4 E-Hybrid', 'Panamera Turbo', 'Panamera Turbo S', 'Sport Turismo', 'Executive', 'GTS'],
    'Taycan': ['Taycan', 'Taycan 4S', 'Taycan Turbo', 'Taycan Turbo S', 'Taycan 4', 'Taycan Cross Turismo', 'Taycan Sport Turismo', 'GTS'],
    '718 Boxster': ['Boxster', 'Boxster S', 'Boxster GTS', 'Boxster Spyder', 'Boxster RS', 'T'],
    '718 Cayman': ['Cayman', 'Cayman S', 'Cayman GTS', 'Cayman GT4', 'Cayman GT4 RS', 'T', 'RS'],
    '918 Spyder': ['Spyder', 'Weissach', 'PHEV'],
  },
  'Bentley': {
    'Continental GT': ['GT', 'GT V8', 'GT W12', 'GT Speed', 'GT Azure', 'GT Mulliner', 'GT Convertible', 'GT Speed Convertible', 'GT Azure Convertible'],
    'Continental GTC': ['GTC', 'GTC V8', 'GTC W12', 'GTC Speed', 'GTC Azure', 'GTC Mulliner'],
    'Flying Spur': ['Spur', 'Spur V8', 'Spur W12', 'Spur Speed', 'Spur Azure', 'Spur Mulliner', 'Hybrid'],
    'Bentayga': ['Bentayga', 'Bentayga V8', 'Bentayga W12', 'Bentayga Speed', 'Bentayga Azure', 'Bentayga Hybrid', 'Bentayga EWB', 'Bentayga S'],
    'Mulsanne': ['Mulsanne', 'Mulsanne Speed', 'Mulsanne Extended', 'Mulsanne Mulliner', 'Mulsanne Grand Bend'],
    'Azure': ['Azure', 'Azure T', 'Azure GT', 'Convertible'],
    'Bacalar': ['Bacalar', 'Mulliner', 'Barchetta'],
    'Batur': ['Batur', 'Batur Black Label', 'Batur Mulliner'],
  },
  'Rolls Royce': {
    'Phantom': ['Phantom', 'Phantom Extended', 'Phantom Drophead', 'Phantom Coupe', 'Series II', 'EWB'],
    'Ghost': ['Ghost', 'Ghost Extended', 'Ghost Black Badge', 'Ghost Series II', 'Ghost V12', 'EWB'],
    'Cullinan': ['Cullinan', 'Cullinan Black Badge', 'Cullinan Series II', 'Cullinan Blue Shadow', 'Cullinan EWB'],
    'Spectre': ['Spectre', 'Spectre Black Badge', 'Spectre EWB', 'Cullinan-based'],
    'Dawn': ['Dawn', 'Dawn Black Badge', 'Dawn Convertible', 'Dawn Aero Cowling', 'Dawn Silver Bullet'],
    'Wraith': ['Wraith', 'Wraith Black Badge', 'Wraith Coupe', 'Wraith Series II', 'EWB'],
    'Silver Cloud': ['Silver Cloud I', 'Silver Cloud II', 'Silver Cloud III', 'Drophead', 'Park Ward'],
    'Silver Ghost': ['Silver Ghost', 'Silver Ghost 40/50', 'Park Ward', 'Humber'],
    'Corniche': ['Corniche', 'Corniche II', 'Corniche III', 'Corniche IV', 'Convertible'],
    'Phantom VIII': ['Phantom VIII', 'Phantom LWB', 'Phantom Coupe', 'Drophead Coupe'],
  },
  'Aston Martin': {
    'DB12': ['DB12', 'DB12 Volante', 'DB12 Coupe', 'DB12 Launch Edition', 'Vantage'],
    'DB11': ['DB11', 'DB11 Volante', 'DB11 Coupe', 'DB11 AMR', 'DB11 V12', 'DB11 V8'],
    'DBS': ['DBS', 'DBS Superleggera', 'DBS Volante', 'DBS Superleggera Volante', 'DBS 770 Ultimate', 'V12'],
    'DB7': ['DB7', 'DB7 Vantage', 'DB7 GT', 'DB7 Zagato', 'DB7 Volante'],
    'DB9': ['DB9', 'DB9 GT', 'DB9 Volante', 'DB9 GT Volante', 'Carbon Edition'],
    'Vantage': ['Vantage', 'Vantage S', 'Vantage Roadster', 'Vantage AMR', 'Vantage F1 Edition', 'Vantage GT4', 'Vantage GT8', 'Vantage GT12', 'V12 Vantage'],
    'Rapide': ['Rapide', 'Rapide S', 'Rapide AMR', 'Rapide E', 'Rapide Carbon Edition'],
    'One-77': ['One-77', 'Quotable', 'Cabriolet'],
    'Valhalla': ['Valhalla', 'PHEV', 'F1-inspired'],
    'Valkyrie': ['Valkyrie', 'Valkyrie Spider', 'AMR Pro', 'Le Mans'],
    'DBX': ['DBX', 'DBX 707', 'DBX 707 Carbon Edition', 'DBX 707 Perf配置', 'DBX STH', 'DBX PHEV'],
    'Zagato': ['Zagato', 'Zagato Volante', 'DBZ', 'DB10'],
  },
  'Bugatti': {
    'Chiron': ['Chiron', 'Chiron Sport', 'Chiron Super Sport', 'Chiron Super Sport 300+', 'Chiron Pur Sport', 'Chiron Noir', 'Chiron Profilée', 'Chiron 110 Ans', 'Chiron Divo', 'Chiron Les Légendes'],
    'Divo': ['Divo', 'Divo No. 1', 'Divo Lord'],
    'Veyron': ['Veyron 16.4', 'Veyron Grand Sport', 'Veyron Super Sport', 'Veyron Super Sport 300+', 'Veyron Grand Sport Vitesse', 'Veyron 16.4 Super Sport', 'Veyron W16', 'Veyron Mansory'],
    'Tourbillon': ['Tourbillon', 'Tourbillon Hyper-Sport', 'PHEV'],
    'Centodieci': ['Centodieci', 'EB110', 'Tribute'],
    'Bolide': ['Bolide', 'Track-only', 'Concept'],
  },
  'Maserati': {
    'Grecale': ['Grecale', 'Grecale Modena', 'Grecale Trofeo', 'Grecale Folgore', 'Grecale GT', 'Grecale PrimaSerie', 'PHEV', 'Electric'],
    'Levante': ['Levante', 'Levante S', 'Levante GTS', 'Levante Trofeo', 'Levante Trofeo Corsa', 'Levante Modena', 'Levante V8', 'PHEV'],
    'Ghibli': ['Ghibli', 'Ghibli S', 'Ghibli V8', 'Ghibli Trofeo', 'Ghibli Modena', 'Ghibli Hybrid', 'GranSport', 'GranLusso'],
    'Quattroporte': ['Quattroporte', 'Quattroporte S', 'Quattroporte GTS', 'Quattroporte Trofeo', 'Quattroporte Modena', 'Quattroporte V8', 'GranLusso', 'Executive'],
    'MC20': ['MC20', 'MC20 Cielo', 'MC20 Stradale', 'MC20 GT2', 'MC20 GT3', 'MC20 Icona', 'Nettuno V6'],
    'GranTurismo': ['GranTurismo', 'GranTurismo S', 'GranTurismo MC Stradale', 'GranTurismo Trofeo', 'GranTurismo Folgore', 'Convertible', 'MC', 'Z'],
    'GranCabrio': ['GranCabrio', 'GranCabrio Trofeo', 'GranCabrio Folgore', 'MC', 'Sport'],
    '3200 GT': ['3200 GT', '3200 GTA', '3200 GT Assetto Corsa', '3200 GT Zagato'],
    'Spyder': ['Spyder', '4200 GT', '4200 Trofeo', 'Cambiocorsa'],
  },
  'Koenigsegg': {
    'Jesko': ['Jesko', 'Jesko Absolut', 'Jesko Attack', 'Jesko Ghost', 'Jesko Carbon', 'Jesko PHEV'],
    'Regera': ['Regera', 'Regera K', 'Regera N', 'Regera Ghost', 'Regera Treble'],
    'Agera': ['Agera', 'Agera R', 'Agera RS', 'Agera One:1', 'Agera S', 'Agera Super Sport'],
    'One:1': ['One:1', 'Megacar', 'Track-only'],
    'Gemera': ['Gemera', 'Gemera PHEV', 'Mega-GT', '4-seater'],
    'CCX': ['CCX', 'CCXR', 'CCXR Trevita', 'CCX Roadster', 'CCXR Edition', 'CCX-R'],
    'CCXR Trevita': ['Trevita', 'Diamond Weave', 'Carbon'],
    'CC8S': ['CC8S', 'CC8S-R', 'Prototype'],
    'Supercars': ['CC8S', 'CCR', 'CCX', 'CCXR', 'Agera', 'One:1', 'Regera', 'Jesko', 'Gemera', 'Tourbillon'],
  },
  'Pagani': {
    'Huayra': ['Huayra', 'Huayra Roadster', 'Huayra BC', 'Huayra BC Roadster', 'Huayra Imola', 'Huayra R', 'Huayra Cinque', 'Huayra Tricolore', 'Huayra Pearl', 'Huayra Codalunga'],
    'Zonda': ['Zonda C12', 'Zonda C12 S', 'Zonda C12 7.3', 'Zonda Roadster', 'Zonda Cinque', 'Zonda Cinque Roadster', 'Zonda F', 'Zonda R', 'Zonda ZO1', 'Zonda HP Barchetta', 'Zonda Aether', 'Zonda Fantasma'],
    'Utopia': ['Utopia', 'Utopia Roadster', 'Manual', 'PHEV'],
    'Imola': ['Imola', 'Roadster', 'Track-only'],
    'Codalunga': ['Codalunga', 'Longtail', 'Coachbuilt'],
  },
  'Lotus': {
    'Emira': ['Emira', 'Emira V6', 'Emira I4', 'Emira First Edition', 'Emira GT4', 'Emira SE', 'Emira Premium', 'Emira Lotus'],
    'Emeya': ['Emeya', 'Emeya S', 'Emeya R', 'Emeya GT', 'Emeya Hyper-GT', 'Electric', 'PHEV'],
    'Eletre': ['Eletre', 'Eletre S', 'Eletre R', 'Eletre GT', 'Eletre Hyper-GT', 'Eletre Carbon', 'Electric', 'PHEV'],
    'Evija': ['Evija', 'Evija X', 'Evija Track', 'Evija Carbon', 'Electric Hypercar'],
    'Exige': ['Exige', 'Exige S', 'Exige Sport', 'Exige Cup', 'Exige Cup 380', 'Exige Cup 420', 'Exige Sport 350', 'Exige V6'],
    'Elise': ['Elise', 'Elise S', 'Elise Sport', 'Elise Cup', 'Elise Cup 250', 'Elise Cup 380', 'Elise 220', 'Elise 250', 'Elise 260'],
    'Evora': ['Evora', 'Evora S', 'Evora Sport', 'Evora GT', 'Evora GT430', 'Evora GT410', 'Evora 400', 'Evora IPS', 'Evora GTE'],
    'Emira GT4': ['GT4', 'Track', 'Racing'],
    '3-Eleven': ['3-Eleven', '3-Eleven 430', 'Road', 'Race'],
  },
  'Abarth': {
    '595': ['595', '595 Competizione', '595 Scorpionearo', '595 Turismo', '595 Essesse', '595 Pista', '595 R', '595 Record'],
    '695': ['695', '695 Competizione', '695 Scorpionearo', '695 Tributo', '695 Anniversario', '695 Biposto', '695 Record'],
    '124 Spider': ['124 Spider', '124 Spider Rally', '124 Spider Abarth', '124 Spider 124 Rally AB', '124 Spider GT'],
    '500': ['500', '500C', '500X', '595', '695'],
    'Punto Evo': ['Punto Evo', 'Punto Evo Abarth', 'Punto SuperSport'],
    'Grande Punto': ['Grande Punto', 'Grande Punto Abarth', 'Grande Punto HGT', 'Abarth SS'],
  },
  'Fiat': {
    '500': ['500', '500C', '500X', '500L', '500L Living', '500L Trekking', '500L Wagon', '500 Hybrid', 'Electric', 'Icon', 'Sport', 'La Prima'],
    '500X': ['500X', '500X Urban', '500X Cross', '500X Sport', '500X Yacht Club', '500X Dolcevita', '500X Hybrid'],
    'Punto': ['Punto', 'Punto Evo', 'Punto GTS', 'Punto Abarth', 'Punto Turbo', 'Punto Sporting'],
    'Tipo': ['Tipo', 'Tipo S-Design', 'Tipo Cross', 'Tipo Street', 'Tipo Hybrid', 'Wagon'],
    'Bravo': ['Bravo', 'Bravo T-Jet', 'Bravo Sport', 'Bravo 1.6', 'Bravo 2.0'],
    'Linea': ['Linea', 'Linea Classic', 'Linea S', 'Linea T-Jet', 'Linea 1.6', 'Linea 2.0'],
    'Ducato': ['Ducato', 'Ducato L1', 'Ducato L2', 'Ducato L3', 'Ducato L4', 'Ducato Maxi', 'Ducato Camper', 'Ducato Van', 'Ducato Passenger'],
    'Fiorino': ['Fiorino', 'Fiorino Cargo', 'Fiorino Combi', 'Fiorino Maxi'],
    'Fullback': ['Fullback', 'Fullback LX', 'Fullback Cross', 'Fullback Sport', 'Pickup', '4WD'],
    '124 Spider': ['124 Spider', '124 Spider Classica', '124 Spider Lusso', '124 Spider Abarth'],
  },
  'Chrysler': {
    '300': ['300', '300 Limited', '300S', '300C', '300 Touring', '300C Platinum', '300 SRT8', '300 SRT Core', '300C V6', '300 V8'],
    'Pacifica': ['Pacifica', 'Pacifica Limited', 'Pacifica Touring L', 'Pacifica Touring X', 'Pacifica Pinnacle', 'Pacifica Hybrid', 'Pacifica Plug-in Hybrid', 'Pacifica Hybrid Limited'],
    'Voyager': ['Voyager', 'Voyager L', 'Voyager LX', 'Voyager Limited', 'Voyager Grand'],
    'Town & Country': ['Town & Country', 'Touring', 'Limited', 'S', 'LXi', 'Touring-L', 'Limited Edition'],
    'Sebring': ['Sebring', 'Sebring Limited', 'Sebring Touring', 'Sebring LX', 'Sebring Convertible', 'Sebring Coupe'],
    'Crossfire': ['Crossfire', 'Crossfire SRT-6', 'Crossfire Roadster', 'SRT-6', 'Limited'],
    'PT Cruiser': ['PT Cruiser', 'PT Cruiser Limited', 'PT Cruiser GT', 'PT Cruiser Street', 'PT Cruiser Classic'],
  },
  'Dodge': {
    'Challenger': ['SXT', 'GT', 'R/T', 'R/T Scat Pack', 'R/T Scat Pack Widebody', 'SRT 392', 'SRT Hellcat', 'SRT Hellcat Redeye', 'SRT Hellcat Redeye Widebody', 'SRT Super Stock', 'R/T Shaker', 'T/A', 'Demon', '170', 'R/T Plus', 'SXT Plus'],
    'Charger': ['SXT', 'GT', 'R/T', 'R/T Scat Pack', 'R/T Scat Pack Widebody', 'SRT 392', 'SRT Hellcat', 'SRT Hellcat Redeye', 'SRT Super Stock', 'Daytona', 'Daytona 392', 'Scat Pack', 'Widebody', 'Police'],
    'Durango': ['SXT', 'GT', 'R/T', 'R/T Plus', 'R/T Scat Pack', 'SRT 392', 'SRT Hellcat', 'SRT Redeye', 'Widebody', 'AWD', 'R/T Tow'],
    'Hornet': ['GT', 'GT Plus', 'R/T', 'R/T Plus', 'Trackhawk', 'PHEV', 'Hybrid'],
    'Journey': ['Journey', 'Journey Crossroad', 'Journey Mainstreet', 'Journey Limited', 'Journey R/T', 'Journey SXT'],
    'Grand Caravan': ['Grand Caravan', 'Grand Caravan SXT', 'Grand Caravan SE', 'Grand Caravan SE Plus', 'Grand Caravan Crew', 'Grand Caravan R/T', 'Grand Caravan GT'],
    'Dart': ['Dart', 'Dart SXT', 'Dart GT', 'Dart Limited', 'Dart Aero', 'Dart Rallye', 'Dart Turbo', 'Dart GTS'],
    'Viper': ['Viper', 'Viper SRT', 'Viper ACR', 'Viper GTS', 'Viper TA', 'Viper 1:32', 'Viper Time Attack', 'Viper ACR Extreme'],
    'Ram': ['1500', '1500 Tradesman', '1500 Express', '1500 SLT', '1500 Bighorn', '1500 Laramie', '1500 Limited', '1500 Rebel', '1500 TRX', '2500', '3500', 'ProMaster'],
  },
  'Cadillac': {
    'Escalade': ['Escalade', 'Escalade Luxury', 'Escalade Premium Luxury', 'Escalade Sport', 'Escalade Platinum', 'Escalade V-Series', 'Escalade ESV', 'Escalade Premium Luxury ESG', 'Escalade 4WD', 'Escalade 2WD'],
    'Escalade ESV': ['ESV', 'ESV Luxury', 'ESV Premium Luxury', 'ESV Platinum', 'ESV Sport', 'ESV V-Series', 'Long Wheelbase'],
    'LYRIQ': ['LYRIQ', 'LYRIQ Luxury', 'LYRIQ Sport', 'LYRIQ Tech', 'LYRIQ AWD', 'RWD', 'Performance', 'Black Crystal'],
    'XT4': ['XT4', 'XT4 Luxury', 'XT4 Premium Luxury', 'XT4 Sport', 'XT4 V-Series', 'FWD', 'AWD'],
    'XT5': ['XT5', 'XT5 Luxury', 'XT5 Premium Luxury', 'XT5 Sport', 'XT5 V-Series', 'FWD', 'AWD'],
    'XT6': ['XT6', 'XT6 Luxury', 'XT6 Premium Luxury', 'XT6 Sport', 'XT6 V-Series', '6-seater', '7-seater'],
    'CT4': ['CT4', 'CT4 Luxury', 'CT4 Premium Luxury', 'CT4 Sport', 'CT4 V-Series', 'CT4 Blackwing', 'RWD', 'AWD'],
    'CT5': ['CT5', 'CT5 Luxury', 'CT5 Premium Luxury', 'CT5 Sport', 'CT5 V-Series', 'CT5 Blackwing', 'CT5-V', 'RWD', 'AWD'],
    'CT6': ['CT6', 'CT6 Luxury', 'CT6 Premium Luxury', 'CT6 Platinum', 'CT6 Sport', 'CT6 V-Series', 'Plug-in Hybrid', 'AWD'],
    'Celestiq': ['Celestiq', 'Celestiq FWD', 'Celestiq AWD', 'Celestiq Ultra Luxury', 'Celestiq Show Car', 'Hand-built'],
  },
  'GMC': {
    'Sierra': ['Sierra', 'Sierra Elevation', 'Sierra SLE', 'Sierra SLT', 'Sierra Denali', 'Sierra AT4', 'Sierra AT4X', 'Sierra Denali Ultimate', 'Sierra 1500', 'Sierra 2500', 'Sierra 3500', 'Pro'],
    'Yukon': ['Yukon', 'Yukon SLE', 'Yukon SLT', 'Yukon Denali', 'Yukon AT4', 'Yukon XL', 'Yukon XL Denali', 'Yukon 4WD', 'Yukon 2WD'],
    'Yukon XL': ['XL', 'XL SLE', 'XL SLT', 'XL Denali', 'XL AT4', 'XL 4WD', 'XL 2WD', 'Long Body'],
    'Acadia': ['Acadia', 'Acadia SLE', 'Acadia SLT', 'Acadia Denali', 'Acadia AT4', 'Acadia FWD', 'Acadia AWD', '7-seater'],
    'Terrain': ['Terrain', 'Terrain SLE', 'Terrain SLT', 'Terrain Denali', 'Terrain AT4', 'Terrain FWD', 'Terrain AWD'],
    'Canyon': ['Canyon', 'Canyon Elevation', 'Canyon SLT', 'Canyon AT4', 'Canyon Denali', 'Canyon 4WD', 'Canyon 2WD'],
    'Hummer EV': ['EV', 'EV 3X', 'EV 2X', 'EV Pickup', 'EV SUV', 'EV Edition 1', 'EV 4WD', 'Traction Mode'],
    'Savana': ['Savana', 'Savana LS', 'Savana LT', 'Savana Cargo', 'Savana Passenger', 'Savana 2500', 'Savana 3500'],
  },
  'Lincoln': {
    'Navigator': ['Navigator', 'Navigator Reserve', 'Navigator Black Label', 'Navigator L', 'Navigator L Reserve', 'Navigator L Black Label', '4WD', 'RWD', 'Hybrid'],
    'Aviator': ['Aviator', 'Aviator Reserve', 'Aviator Black Label', 'Aviator Grand Touring', 'Aviator PHEV', 'Aviator 4WD', 'Aviator RWD'],
    'Corsair': ['Corsair', 'Corsair Reserve', 'Corsair Black Label', 'Corsair Grand Touring', 'Corsair PHEV', 'Corsair AWD', 'Corsair FWD'],
    'Nautilus': ['Nautilus', 'Nautilus Reserve', 'Nautilus Black Label', 'Nautilus Hybrid', 'Nautilus PHEV', 'Nautilus AWD', 'Nautilus FWD'],
    'MKZ': ['MKZ', 'MKZ Reserve', 'MKZ Black Label', 'MKZ Hybrid', 'MKZ AWD', 'MKZ FWD', 'MKZ 3.0T'],
    'MKC': ['MKC', 'MKC Reserve', 'MKC Black Label', 'MKC AWD', 'MKC FWD', 'MKC 2.0T', 'MKC 2.3T'],
    'MKS': ['MKS', 'MKS Reserve', 'MKS EcoBoost', 'MKS AWD', 'MKS FWD'],
    'MKT': ['MKT', 'MKT Town Car', 'MKT 3.5L', 'MKT EcoBoost', 'MKT AWD'],
    'Town Car': ['Town Car', 'Town Car Executive', 'Town Car L', 'Town Car Signature', 'Town Car Cartier'],
    'Continental': ['Continental', 'Continental Reserve', 'Continental Black Label', 'Continental 3.0T', 'Continental AWD', 'Continental FWD'],
  },
  'Infiniti': {
    'Q50': ['Q50', 'Q50 Luxe', 'Q50 Sport', 'Q50 Red Sport', 'Q50 Sensory', 'Q50 Essential', 'Q50 3.0T', 'Q50 Hybrid', 'RWD', 'AWD'],
    'Q60': ['Q60', 'Q60 Luxe', 'Q60 Sport', 'Q60 Red Sport', 'Q60 Sensory', 'Q60 3.0T', 'Q60 AWD', 'RWD', 'Convertible'],
    'QX50': ['QX50', 'QX50 Luxe', 'QX50 Sensory', 'QX50 Essential', 'QX50 ProACTIVE', 'QX50 Autograph', 'QX50 AWD', 'QX50 FWD'],
    'QX55': ['QX55', 'QX55 Luxe', 'QX55 Sensory', 'QX55 Essential', 'QX55 Sport', 'QX55 AWD', 'QX55 FWD', 'Coupé SUV'],
    'QX60': ['QX60', 'QX60 Luxe', 'QX60 Sensory', 'QX60 Essential', 'QX60 Autograph', 'QX60 AWD', 'QX60 FWD', '7-seater'],
    'QX70': ['QX70', 'QX70 Luxe', 'QX70 Sport', 'QX70 S', 'QX70 AWD', 'RWD'],
    'QX80': ['QX80', 'QX80 Luxe', 'QX80 Sensory', 'QX80 Essential', 'QX80 Premium Select', 'QX80 AWD', 'RWD', '4WD'],
    'Q70': ['Q70', 'Q70 Luxe', 'Q70 Sport', 'Q70 Hybrid', 'Q70 3.7L', 'Q70 5.6L', 'Q70 AWD', 'RWD'],
    'Q40': ['Q40', 'Q40 Sport', 'Q40 Luxury', 'Q40 AWD', 'RWD'],
    'Q45': ['Q45', 'Q45 Luxury', 'Q45 Sport', 'Q45 Premium', 'Q45 AWD', 'RWD'],
  },
  // REMAINING BRANDS
  'Arcfox': {
    'Alpha S': ['Comfort', 'Luxury', 'Premium', 'Performance', 'EV'],
    'Alpha T': ['Comfort', 'Luxury', 'Premium', 'Performance', 'EV'],
    'GT': ['GT', 'Sport', 'Performance', 'EV'],
    'ECF': ['Comfort', 'Luxury', 'Premium', 'EV'],
  },
  'Bestune': {
    'T77': ['Comfort', 'Luxury', 'Premium', 'Premium+'],
    'T55': ['Comfort', 'Luxury', 'Premium'],
    'B70': ['Comfort', 'Luxury', 'Premium'],
    'T90': ['Comfort', 'Luxury', 'Premium', 'Premium+'],
    'T99': ['Comfort', 'Luxury', 'Premium', 'Premium+', '7-seater'],
  },
  'Borgward': {
    'BX5': ['Comfort', 'Luxury', 'Premium'],
    'BX7': ['Comfort', 'Luxury', 'Premium', 'Premium+'],
    'BX6': ['Comfort', 'Luxury', 'Premium'],
  },
  'Brilliance': {
    'FRV': ['Comfort', 'Luxury', 'Premium'],
    'V5': ['Comfort', 'Luxury', 'Premium'],
    'H530': ['Comfort', 'Luxury', 'Premium'],
  },
  'Caterham': {
    'Seven': ['Seven 270', 'Seven 310', 'Seven 420', 'Seven 485', 'Road', 'Sport', 'Classic'],
    'Seven 270': ['270', 'SR', 'CSR'],
    'Seven 310': ['310', 'SR', 'CSR'],
    'Seven 420': ['420', '420R', 'SR'],
    'Seven 485': ['485', '485R', 'SR'],
  },
  'DFSK': {
    'Fengon 580': ['Comfort', 'Luxury', 'Premium', '7-seater'],
    'Fengon 500': ['Comfort', 'Luxury', 'Premium'],
    'Fengon 600': ['Comfort', 'Luxury', 'Premium', '7-seater'],
    'Fengon ix5': ['Comfort', 'Luxury', 'Premium'],
    'H30 Cross': ['Comfort', 'Luxury', 'Premium'],
  },
  'Dongfeng': {
    'AX7': ['Comfort', 'Luxury', 'Premium'],
    'Shine Max': ['Comfort', 'Luxury', 'Premium'],
    'Shine Mage': ['Comfort', 'Luxury', 'Premium'],
    'S30': ['Comfort', 'Luxury', 'Premium'],
  },
  'Dorcen': {
    'G70': ['Comfort', 'Luxury', 'Premium'],
    'G60': ['Comfort', 'Luxury', 'Premium'],
    'S60': ['Comfort', 'Luxury', 'Premium'],
  },
  'Fisker': {
    'Ocean': ['Ocean', 'Ocean Extreme', 'Ocean Ultimate', 'Ocean One', 'EV'],
    'Karma': ['Karma', 'Karma EcoSport', 'Karma Luxury', 'Karma Performance'],
    'Ronin': ['Ronin', 'Ronin GT', 'Ronin Performance'],
  },
  'Forthing': {
    'T5': ['Comfort', 'Luxury', 'Premium'],
    'T5 EVO': ['Comfort', 'Luxury', 'Premium', 'Sport'],
    'M4': ['Comfort', 'Luxury', 'Premium', '7-seater'],
    'U-Tour': ['Comfort', 'Luxury', 'Premium', '7-seater'],
  },
  'Foton': {
    'Tunland': ['Comfort', 'Luxury', 'Premium', '4WD', 'Pickup'],
    'View': ['Comfort', 'Luxury', 'Premium', '4WD'],
    'Aumark': ['Comfort', 'Luxury', 'Premium', 'Truck'],
  },
  'Hummer': {
    'H2': ['H2', 'H2 Luxury', 'H2 Performance', 'H2 Off-Road'],
    'H3': ['H3', 'H3 Luxury', 'H3 Performance', 'H3 Off-Road'],
    'EV': ['EV', 'EV 3X', 'EV 2X', 'EV Edition 1', 'Pickup', 'SUV'],
    'EV SUV': ['EV SUV', 'EV SUV 3X', 'EV SUV 2X'],
  },
  'Isuzu': {
    'D-Max': ['DX', 'LX', 'V-Cross', '4WD', 'RWD', 'Single Cab', 'Double Cab'],
    'MU-X': ['LS-M', 'LS-T', '4WD', 'RWD', '7-seater'],
    'Trooper': ['JS', 'JLX', 'Premium'],
  },
  'Kaiyi': {
    'X3': ['Comfort', 'Luxury', 'Premium'],
    'X3 Pro': ['Comfort', 'Luxury', 'Premium'],
    'X7': ['Comfort', 'Luxury', 'Premium'],
    'E5': ['Comfort', 'Luxury', 'Premium', 'EV'],
  },
  'King Long': {
    'XMQ': ['XMQ6127', 'XMQ6180', 'XMQ6125', 'Coach', 'Bus'],
    'XML': ['XML6125', 'XML6180', 'Coach', 'Bus'],
  },
  'KTM': {
    'X-Bow': ['X-Bow', 'X-Bow S', 'X-Bow R', 'X-Bow GT', 'X-Bow Sport', 'X-Bow Track'],
  },
  'LS Auto': {
    'LS500': ['Comfort', 'Luxury', 'Premium', 'F Sport'],
    'LS350': ['Comfort', 'Luxury', 'Premium'],
    'UX200': ['Comfort', 'Luxury', 'Premium'],
  },
  'Lucid': {
    'Air': ['Pure', 'Touring', 'Grand Touring', 'Sapphire', 'EV', 'AWD'],
    'Gravity': ['Pure', 'Touring', 'Grand Touring', 'EV', 'AWD'],
    'Sapphire': ['Sapphire', 'Performance', 'Track', 'EV'],
  },
  'Luxgen': {
    'U6': ['Comfort', 'Luxury', 'Premium', 'GT'],
    'U7': ['Comfort', 'Luxury', 'Premium', '7-seater'],
    'S5': ['Comfort', 'Luxury', 'Premium'],
  },
  'Lynk & Co': {
    '01': ['Plus', 'Pro', 'Premium', 'HEV', 'PHEV'],
    '02': ['Plus', 'Pro', 'Premium', 'HEV'],
    '03': ['Plus', 'Pro', 'Premium', '03+', 'PHEV'],
    '05': ['Plus', 'Pro', 'Premium', 'PHEV'],
    '06': ['Plus', 'Pro', 'Premium', 'HEV'],
    '08': ['Plus', 'Pro', 'Premium', 'PHEV', 'EM-P'],
    '09': ['Plus', 'Pro', 'Premium', 'PHEV', '7-seater'],
  },
  'Mahindra': {
    'Scorpio': ['S3', 'S5', 'S7', 'S11', '4WD', 'RWD'],
    'XUV500': ['W4', 'W6', 'W8', 'W10', '4WD'],
    'XUV300': ['W4', 'W6', 'W8', 'W10', '4WD'],
    'Thar': ['LX', 'AX', 'LX 4WD', 'AX 4WD', 'RWD', '4WD'],
    'Bolero': ['S2', 'S4', 'S6', 'S11', '4WD'],
    'XUV700': ['MX', 'AX', 'LX', '4WD', 'AWD', '7-seater'],
  },
  'Maxus': {
    'T60': ['Comfort', 'Luxury', 'Premium', '4WD', 'Pickup'],
    'T70': ['Comfort', 'Luxury', 'Premium', '4WD', 'Pickup'],
    'T90': ['Comfort', 'Luxury', 'Premium', '4WD', 'Pickup'],
    'G10': ['Comfort', 'Luxury', 'Premium', '7-seater', 'Van'],
    'G50': ['Comfort', 'Luxury', 'Premium', '7-seater', 'MPV'],
    'G90': ['Comfort', 'Luxury', 'Premium', '7-seater', 'MPV'],
    'Mifa': ['Mifa 9', 'Mifa 7', 'Mifa 5', 'EV', 'MPV'],
  },
  'Maybach': {
    'S-Class': ['S 480', 'S 560', 'S 580', 'S 680', 'Pullman', '4MATIC'],
    'GLS': ['GLS 480', 'GLS 600', '4MATIC', 'Maybach'],
    '57': ['S 570', 'S 600', 'LWB'],
    '62': ['S 620', 'S 650', 'LWB', 'S 680'],
  },
  'Morgan': {
    'Plus Four': ['Plus Four', 'Plus Four CX-T', 'Plus Four Track'],
    'Plus Six': ['Plus Six', 'Plus Six CX-T', 'Plus Six Track'],
    '3 Wheeler': ['3 Wheeler', '3 Wheeler S', '3 Wheeler X'],
  },
  'Noble': {
    'M600': ['M600', 'M600 Turbo', 'M600 Bi-Turbo'],
    'M500': ['M500', 'M500 Turbo'],
    'M15': ['M15', 'M15 GT'],
  },
  'Oullim': {
    'Spirra': ['Spirra', 'Spirra S', 'Spirra N', 'GT', 'Turbo'],
  },
  'Polestar': {
    '1': ['Polestar 1', 'Polestar 1 Gold', 'Polestar 1 Performance', 'PHEV'],
    '2': ['Standard', 'Long Range', 'Dual Motor', 'Performance', 'BST', 'EV'],
    '3': ['Long Range', 'Dual Motor', 'Performance', 'EV', 'AWD'],
    '4': ['Long Range', 'Dual Motor', 'Performance', 'EV', 'AWD'],
  },
  'Proton': {
    'Saga': ['Standard', 'Executive', 'Premium', 'S'],
    'Iriz': ['Standard', 'Executive', 'Premium', 'R3'],
    'Persona': ['Standard', 'Executive', 'Premium', 'Premium X'],
    'Exora': ['Standard', 'Executive', 'Premium', 'Prime'],
    'X70': ['Standard', 'Executive', 'Premium', 'X90'],
    'X50': ['Standard', 'Executive', 'Premium', 'X90'],
  },
  'Rabdan': {
    'One': ['One', 'One Premium', 'One Performance', 'EV'],
  },
  'Ram': {
    '1500': ['Tradesman', 'Big Horn', 'Laramie', 'Limited', 'Rebel', 'TRX', '4WD', 'RWD'],
    '2500': ['Tradesman', 'Power Wagon', 'Laramie', 'Limited', '4WD'],
    '3500': ['Tradesman', 'Laramie', 'Limited', 'Dually', '4WD'],
    'ProMaster': ['ProMaster 1500', 'ProMaster 2500', 'ProMaster 3500', 'Van', 'Cargo'],
  },
  'Roewe': {
    'RX5': ['Comfort', 'Luxury', 'Premium', 'Premium+'],
    'RX5 MAX': ['Comfort', 'Luxury', 'Premium', 'Premium+'],
    'RX8': ['Comfort', 'Luxury', 'Premium', '4WD'],
    'i5': ['Comfort', 'Luxury', 'Premium'],
    'iMAX8': ['Comfort', 'Luxury', 'Premium', '7-seater'],
    'Marvel X': ['Comfort', 'Luxury', 'Premium', 'EV'],
  },
  'Saab': {
    '9-3': ['Linear', 'Vector', 'Aero', 'Turbo X', 'Griffin'],
    '9-5': ['Linear', 'Vector', 'Aero', 'Turbo X', 'Griffin'],
    '9-4X': ['Linear', 'Vector', 'Aero'],
  },
  'Seat': {
    'Leon': ['Reference', 'Style', 'FR', 'Cupra', 'Xcellence', 'e-Hybrid'],
    'Arona': ['Reference', 'Style', 'FR', 'Xcellence', 'Cupra'],
    'Ateca': ['Reference', 'Style', 'FR', 'Xcellence', 'Cupra', '4Drive'],
    'Tarraco': ['Reference', 'Style', 'FR', 'Xcellence', '4Drive', '7-seater'],
    'Ibiza': ['Reference', 'Style', 'FR', 'Xcellence'],
  },
  'Seres': {
    'SF5': ['Comfort', 'Luxury', 'Premium', 'EV', 'PHEV', '4WD'],
    'SF7': ['Comfort', 'Luxury', 'Premium', 'EV', '4WD'],
    'M3': ['Comfort', 'Luxury', 'Premium', 'EV'],
  },
  'Skywell': {
    'ET5': ['Comfort', 'Luxury', 'Premium', 'EV'],
    'U75': ['Comfort', 'Luxury', 'Premium', 'EV'],
  },
  'Smart': {
    'Fortwo': ['Pure', 'Pulse', 'Prime', 'Proxy', 'BRABUS', 'Electric'],
    'Forfour': ['Pure', 'Pulse', 'Prime', 'Proxy', 'Electric'],
    '#1': ['Pro', 'Premium', 'Pulse', 'BRABUS', 'Electric'],
    '#3': ['Pro', 'Premium', 'Pulse', 'BRABUS', 'Electric'],
  },
  'Soueast': {
    'T5': ['Comfort', 'Luxury', 'Premium'],
    'T6': ['Comfort', 'Luxury', 'Premium', '4WD'],
    'S3': ['Comfort', 'Luxury', 'Premium'],
    'S5': ['Comfort', 'Luxury', 'Premium'],
  },
  'Spyker': {
    'C8': ['C8', 'C8 Laviolette', 'C8 Spyder', 'C8 Aileron', 'C8 Preliator'],
    'C12': ['C12 Zagato', 'C12 LWB'],
  },
  'Ssangyong': {
    'Tivoli': ['Sapphire', 'Quartz', 'Diamond', '4WD'],
    'XLV': ['Sapphire', 'Quartz', 'Diamond', '4WD', '7-seater'],
    'Korando': ['Sapphire', 'Quartz', 'Diamond', '4WD'],
    'Rexton': ['Sapphire', 'Quartz', 'Diamond', '4WD', '7-seater'],
    'Musso': ['Sapphire', 'Quartz', 'Diamond', '4WD', 'Pickup'],
  },
  'Tata': {
    'Nexon': ['XE', 'XM', 'XZ', 'XZ+', 'XZ+ Lux', '4WD'],
    'Punch': ['XE', 'XM', 'XZ', 'XZ+', 'Creative', 'Pure'],
    'Harrier': ['XE', 'XM', 'XZ', 'XZ+', 'XZ+ Dark', '4WD'],
    'Safari': ['XE', 'XM', 'XZ', 'XZ+', 'XZ+ Dark', '4WD', '7-seater'],
    'Altroz': ['XE', 'XM', 'XZ', 'XZ+', 'Turbo'],
    'Tiago': ['XE', 'XM', 'XZ', 'XZ+', 'NRG', 'EV'],
  },
  'VinFast': {
    'VF 8': ['Eco', 'Plus', 'EV', 'AWD'],
    'VF 9': ['Eco', 'Plus', 'EV', 'AWD', '7-seater'],
    'VF 6': ['Eco', 'Plus', 'EV'],
    'VF 7': ['Eco', 'Plus', 'EV', 'AWD'],
    'VF e34': ['Eco', 'Plus', 'EV'],
  },
  'Zotye': {
    'T600': ['Comfort', 'Luxury', 'Premium'],
    'T700': ['Comfort', 'Luxury', 'Premium'],
    'Z100': ['Comfort', 'Luxury'],
    'Z300': ['Comfort', 'Luxury', 'Premium'],
    'Z500': ['Comfort', 'Luxury', 'Premium'],
    'E200': ['Comfort', 'Luxury', 'EV'],
  },
  // MISSING BRANDS
  'Daihatsu': {
    'Terios': ['X', 'S', 'SS', 'R', 'RX', '4WD'],
    'Sirion': ['X', 'S', 'SR', 'ST', 'Custom'],
    'YRV': ['X', 'S', 'ST', 'Turbo'],
    'Materia': ['X', 'S', 'SX', 'Turbo'],
    'Charade': ['X', 'S', 'SE', 'Turbo'],
    'Gran Max': ['Std', 'DX', 'Luxury', 'Truck', 'Van'],
  },
  'International': {
    'MXT': ['MXT', 'MXT-L', '4WD', '6x6'],
    'CXT': ['CXT', 'CXT-L', '4WD'],
  },
  'Livan': {
    'X6 Pro': ['Comfort', 'Luxury', 'Premium', 'AWD'],
    'S6 Pro': ['Comfort', 'Luxury', 'Premium', 'AWD'],
    'X3': ['Comfort', 'Luxury', 'Premium'],
  },
  'MINI': {
    'Cooper': ['One', 'Cooper', 'Cooper S', 'John Cooper Works', 'Electric'],
    'Countryman': ['One', 'Cooper', 'Cooper S', 'John Cooper Works', 'All4', 'Electric'],
    'Clubman': ['One', 'Cooper', 'Cooper S', 'John Cooper Works', 'All4'],
    'Convertible': ['One', 'Cooper', 'Cooper S', 'John Cooper Works'],
    'Hardtop': ['One', 'Cooper', 'Cooper S', 'John Cooper Works', 'Electric'],
    'John Cooper Works': ['JCW', 'JCW Pro', 'GP'],
  },
  'Mercury': {
    'Grand Marquis': ['GS', 'LS', 'Premier', 'Colony Park'],
    'Mountaineer': ['Base', 'Premier', 'Luxury', '4WD'],
    'Milan': ['I4', 'V6', 'Premier', 'Hybrid'],
    'Mariner': ['I4', 'V6', 'Premier', 'Hybrid', '4WD'],
    'Montego': ['Luxury', 'Premier', 'AWD'],
  },
};

export const POPULAR_MAKES: string[] = [
  "Toyota", "Nissan", "Hyundai", "Honda", "Ford",
  "Mercedes-Benz", "BMW", "Audi", "Kia", "Mazda",
];

export const getModelsByMake = (make: string): string[] => carModels[make] || [];
export const getTrimsForModel = (make: string, model: string): string[] => carTrims[make]?.[model] || [];